### ISSUE TITLE
increasing mutation rate causes estimate to abort

### ISSUE THREAD

**Issue by mmaalvarez** [popgenmethods/smcpp#113]
I was running the estimate command using μ = 1.25e-8 and it worked. However, changing it to μ = 1.61e-8 caused it to unexpectedly abort. After retrying it kept failing. The ending of the log follows:

9957693 smcpp.optimize.plugins.progress_printer INFO EM iteration 3 of 20...
9957693 smcpp.analysis.base INFO Running E-step
10689622 smcpp.analysis.base INFO E-step completed
10689691 smcpp.optimize.plugins.loglikelihood_monitor INFO New loglik: -9816598.645892	(old: -9865329.676793 [0.493963%])
10700584 smcpp.optimize.plugins.parameter_optimizer INFO Updating rho, bounds (0.000001, 0.010000)
10703845 smcpp.optimize.plugins.parameter_optimizer INFO New rho: 0.00235229
basinhopping step 0: f 1.00213e+07
basinhopping step 1: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 2: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 3: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 4: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 5: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 6: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 7: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 8: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 9: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 10: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 11: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 12: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 13: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 14: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 15: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 16: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 17: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 18: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 19: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 20: f 1.00213e+07 trial_f 1.00213e+07 accepted 1  lowest_f 1.00213e+07
basinhopping step 0: f 1.01639e+07
basinhopping step 1: f 1.01638e+07 trial_f 1.01638e+07 accepted 1  lowest_f 1.01638e+07
found new global minimum on step 1 with function value 1.01638e+07
basinhopping step 2: f 1.01638e+07 trial_f 1.01638e+07 accepted 1  lowest_f 1.01638e+07
basinhopping step 3: f 1.01638e+07 trial_f 1.01638e+07 accepted 0  lowest_f 1.01638e+07
basinhopping step 4: f 1.01638e+07 trial_f 1.01639e+07 accepted 0  lowest_f 1.01638e+07
basinhopping step 5: f 1.01638e+07 trial_f 1.01638e+07 accepted 0  lowest_f 1.01638e+07
basinhopping step 6: f 1.01638e+07 trial_f 1.01639e+07 accepted 0  lowest_f 1.01638e+07
basinhopping step 7: f 1.01638e+07 trial_f 1.01638e+07 accepted 1  lowest_f 1.01638e+07
found new global minimum on step 7 with function value 1.01638e+07
basinhopping step 8: f 1.01638e+07 trial_f 1.01638e+07 accepted 1  lowest_f 1.01638e+07
found new global minimum on step 8 with function value 1.01638e+07
basinhopping step 9: f 1.01638e+07 trial_f 1.01638e+07 accepted 1  lowest_f 1.01638e+07
basinhopping step 10: f 1.01638e+07 trial_f 1.01638e+07 accepted 0  lowest_f 1.01638e+07
basinhopping step 11: f 1.01638e+07 trial_f 1.01639e+07 accepted 0  lowest_f 1.01638e+07
warning: basinhopping: local minimization failure
basinhopping step 12: f 1.01638e+07 trial_f 1.01639e+07 accepted 0  lowest_f 1.01638e+07
basinhopping step 13: f 1.01638e+07 trial_f 1.01638e+07 accepted 0  lowest_f 1.01638e+07
basinhopping step 14: f 1.01638e+07 trial_f 1.01638e+07 accepted 1  lowest_f 1.01638e+07
basinhopping step 15: f 1.01638e+07 trial_f 1.01638e+07 accepted 1  lowest_f 1.01638e+07
found new global minimum on step 15 with function value 1.01638e+07
warning: basinhopping: local minimization failure
basinhopping step 16: f 1.01638e+07 trial_f 1.01639e+07 accepted 0  lowest_f 1.01638e+07
basinhopping step 17: f 1.01638e+07 trial_f 1.01639e+07 accepted 0  lowest_f 1.01638e+07
basinhopping step 18: f 1.01638e+07 trial_f 1.01638e+07 accepted 0  lowest_f 1.01638e+07
basinhopping step 19: f 1.01638e+07 trial_f 1.01638e+07 accepted 0  lowest_f 1.01638e+07
basinhopping step 20: f 1.01638e+07 trial_f 1.01638e+07 accepted 0  lowest_f 1.01638e+07
Traceback (most recent call last):
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/ad/admath/admath.py", line 160, in vectorized_function
    return [vectorized_function(xi, **kwargs) for xi in x]
TypeError: 'ADF' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/ad/admath/admath.py", line 160, in vectorized_function
    return [vectorized_function(xi, **kwargs) for xi in x]
TypeError: 'numpy.float64' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/CONDA/4.3.11_PYTHON3/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.14.0.dev0', 'console_scripts', 'smc++')()
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/smcpp/commands/estimate.py", line 75, in main
    analysis.run()
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/smcpp/analysis/base.py", line 109, in run
    self._optimizer.run(niter or self._niter)
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/smcpp/optimize/optimizers.py", line 165, in run
    res = self._minimize(x0, coords)
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/smcpp/optimize/optimizers.py", line 121, in _minimize
    niter=20)
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/scipy/optimize/_basinhopping.py", line 670, in basinhopping
    accept_tests, disp=disp)
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/scipy/optimize/_basinhopping.py", line 75, in __init__
    minres = minimizer(self.x)
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/scipy/optimize/_basinhopping.py", line 287, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/scipy/optimize/_minimize.py", line 603, in minimize
    callback=callback, **options)
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/scipy/optimize/lbfgsb.py", line 335, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/scipy/optimize/lbfgsb.py", line 285, in func_and_grad
    f = fun(x, *args)
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 293, in function_wrapper
    return function(*(wrapper_args + args))
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/smcpp/optimize/optimizers.py", line 65, in _f
    self[coords] = xs
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/smcpp/optimize/optimizers.py", line 39, in __setitem__
    self._analysis.model[coords] = x
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/smcpp/model.py", line 166, in __setitem__
    self.update_observers('model update')
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/smcpp/observe.py", line 44, in update_observers
    observer.update(*args, **kwargs)
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/smcpp/observe.py", line 17, in wrapper
    wrapped(*args, **kwargs)
  File "smcpp/_smcpp.pyx", line 336, in smcpp._smcpp.PyOnePopInferenceManager.update
  File "smcpp/_smcpp.pyx", line 84, in smcpp._smcpp.make_params_from_model
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/smcpp/model.py", line 203, in stepwise_values
    ret = np.clip(self(np.cumsum(self.s)),
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/smcpp/model.py", line 184, in __call__
    ad.admath.exp(self._spline(self._trans(x)))
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/ad/admath/admath.py", line 160, in vectorized_function
    return [vectorized_function(xi, **kwargs) for xi in x]
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/ad/admath/admath.py", line 160, in <listcomp>
    return [vectorized_function(xi, **kwargs) for xi in x]
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/ad/admath/admath.py", line 162, in vectorized_function
    return func(x, **kwargs)
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/ad/admath/admath.py", line 794, in exp
    f = exp(x)
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/ad/admath/admath.py", line 162, in vectorized_function
    return func(x, **kwargs)
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/ad/admath/admath.py", line 829, in exp
    return math.exp(x.real)
OverflowError: math range error
   may possibly be caused by a bad search direction.
 This problem is unconstrained.

 Warning:  more than 10 function and gradient
   evaluations in the last line search.  Termination
   may possibly be caused by a bad search direction.
 This problem is unconstrained.

 Bad direction in the line search;
   refresh the lbfgs memory and restart the iteration.

 Warning:  more than 10 function and gradient
   evaluations in the last line search.  Termination
   may possibly be caused by a bad search direction.
 This problem is unconstrained.

 Warning:  more than 10 function and gradient
   evaluations in the last line search.  Termination
   may possibly be caused by a bad search direction.
 This problem is unconstrained.

 Bad direction in the line search;
   refresh the lbfgs memory and restart the iteration.

At iterate   10    f=  1.01638D+07    |proj g|=  1.20342D+02

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    8     10     50      1     0     0   1.203D+02   1.016D+07
  F =   10163846.318367412     

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH             

 Cauchy                time 0.000E+00 seconds.
 Subspace minimization time 0.000E+00 seconds.
 Line search           time 0.000E+00 seconds.

 Total User time 0.000E+00 seconds.

RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            8     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  1.04392D+07    |proj g|=  8.24971D+03

At iterate    1    f=  1.04381D+07    |proj g|=  1.43673D+03

At iterate    2    f=  1.04376D+07    |proj g|=  2.12256D+03

At iterate    3    f=  1.04376D+07    |proj g|=  1.90161D+03

At iterate    4    f=  1.04376D+07    |proj g|=  1.78934D+03

At iterate    5    f=  1.04376D+07    |proj g|=  1.78501D+03

**Comment by terhorst** [comment]
Can do enable debugging by using `-vv` and post the output here?

**Comment by mmaalvarez** [comment]
I am trying the last version and the command cv instead of estimate. It keeps failing, but with the error:

`RuntimeError: erroneous average coalescence time`

The log file is attached:
[log.txt](https://github.com/popgenmethods/smcpp/files/2967789/log.txt)

**Comment by terhorst** [comment]
Can you try re-running vcf2smc while using the [`-c` option](https://github.com/popgenmethods/smcpp#optional-arguments)? From the log, there are some long runs of homozygosity which lead to the effective population size in the recent past to approach zero, eventually causing a numerical error. The length distribution of these runs (~100-200kb) is longer than I would expect in a randomly mating sample of size 20; do you know if your sample is inbred?

**Comment by mmaalvarez** [comment]
Thanks, I will try that. 
The population I sampled has higher rates of inbreeding when compared to surrounding populations, although any 1st or 2nd degree relatives have been removed.

**Comment by terhorst** [comment]
(I should add that I am assuming based on your choice of mutation rate that these are humans)

**Comment by mmaalvarez** [comment]
Using the -c 100000 option in vcf2smc instead of masking seems to work. And yes, these are humans. Thanks for your help!
