### ISSUE TITLE
smc++ cv error: FloatingPointError: divide by zero encountered in log

### ISSUE THREAD

**Issue by Yung-Chien** [popgenmethods/smcpp#123]
Dear @terhorst :
I am trying to use cv module to fix the model like this:

`smc++ cv -o analysis/ 1.25e-8 chr*.smc.gz `

I got this error:

`1446 smcpp.analysis.base INFO theta: 0.000100
1447 smcpp.analysis.base INFO rho: 0.000100
1447 smcpp.data_filter INFO Loading data...
1517 smcpp.data_filter INFO 0.04 Gb of data
1518 smcpp.data_filter INFO 1 population
1519 smcpp.estimation_tools WARNING Long runs of homozygosity in contig chr01.smc.gz: 
[39509623] (base pairs)
Traceback (most recent call last):
  File "/home1/lyj/miniconda2/envs/smcpp/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.15.2', 'console_scripts', 'smc++')()
  File "/home1/lyj/miniconda2/envs/smcpp/lib/python3.6/site-packages/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/home1/lyj/miniconda2/envs/smcpp/lib/python3.6/site-packages/smcpp/commands/cv.py", line 75, in main
    test = Analysis([args.data[j] for j in range(L) if j in fold], args)
  File "/home1/lyj/miniconda2/envs/smcpp/lib/python3.6/site-packages/smcpp/analysis/analysis.py", line 29, in __init__
    m[:] = np.log(NeN0)
FloatingPointError: divide by zero encountered in log`

How do I fix this error?Thanks.

The version of my smcpp is 1.15.2, and python is 3.6.9.

Yung-Chien

**Comment by Yung-Chien** [comment]
okay, I would like re-upload the error log 

1446 smcpp.analysis.base INFO theta: 0.000100
1447 smcpp.analysis.base INFO rho: 0.000100
1447 smcpp.data_filter INFO Loading data...
1517 smcpp.data_filter INFO 0.04 Gb of data
1518 smcpp.data_filter INFO 1 population
1519 smcpp.estimation_tools WARNING Long runs of homozygosity in contig chr01.smc.gz: 
[39509623] (base pairs)
Traceback (most recent call last):
  File "/home1/lyj/miniconda2/envs/smcpp/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.15.2', 'console_scripts', 'smc++')()
  File "/home1/lyj/miniconda2/envs/smcpp/lib/python3.6/site-packages/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/home1/lyj/miniconda2/envs/smcpp/lib/python3.6/site-packages/smcpp/commands/cv.py", line 75, in main
    test = Analysis([args.data[j] for j in range(L) if j in fold], args)
  File "/home1/lyj/miniconda2/envs/smcpp/lib/python3.6/site-packages/smcpp/analysis/analysis.py", line 29, in __init__
    m[:] = np.log(NeN0)
FloatingPointError: divide by zero encountered in log

**Comment by terhorst** [comment]
This is a data quality issue. The lines 

> 1517 smcpp.data_filter INFO 0.04 Gb of data
> 1518 smcpp.data_filter INFO 1 population
> 1519 smcpp.estimation_tools WARNING Long runs of homozygosity in contig chr01.smc.gz:
> [39509623] (base pairs)

indicate that nearly 100% of the chromosome you are attempting to analyze is homozygous. As SMC++ uses variation data to estimate size history, this means that there is no signal available to analyze. You might want to double-check that nothing went wrong earlier in your data processing pipeline.

**Comment by terhorst** [comment]
This is a data quality issue. The lines

> 1517 smcpp.data_filter INFO 0.04 Gb of data
> 1518 smcpp.data_filter INFO 1 population
> 1519 smcpp.estimation_tools WARNING Long runs of homozygosity in contig chr01.smc.gz:
> [39509623] (base pairs)

indicate that nearly 100% of the chromosome you are attempting to analyze is homozygous. As SMC++ uses variation to estimate size history, this means that there is no signal in your data. You might want to double-check that nothing went wrong earlier in your processing pipeline.
