### ISSUE TITLE
questions when using vcf2smc 

### ISSUE THREAD

**Issue by Yafei-Guo-coder** [popgenmethods/smcpp#136]
hi dear @terhorst：
when i use the vcf2smc with your example.csv, with the commond below:
smc++ vcf2smc example.vcf.gz chr1.smc.gz pop1:msp_0,msp_1,msp_2,msp_3,msp_4
and it returns some error information:

Traceback (most recent call last):
  File "/data1/home/yafei/Software/anaconda3/envs/smcpp/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.15.3', 'console_scripts', 'smc++')()
  File "/data1/home/yafei/Software/anaconda3/envs/smcpp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/data1/home/yafei/Software/anaconda3/envs/smcpp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/data1/home/yafei/Software/anaconda3/envs/smcpp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/data1/home/yafei/Software/anaconda3/envs/smcpp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/data1/home/yafei/Software/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/frontend/console.py", line 3, in <module>
    from .. import commands, logging, version, defaults, _smcpp
  File "/data1/home/yafei/Software/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/commands/__init__.py", line 1, in <module>
    from . import vcf2smc, estimate, split, chunk, cite, plot, \
  File "/data1/home/yafei/Software/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/commands/vcf2smc.py", line 7, in <module>
    from pysam import VariantFile, TabixFile
  File "/data1/home/yafei/Software/anaconda3/envs/smcpp/lib/python3.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /data1/home/yafei/Software/anaconda3/envs/smcpp/lib/python3.7/site-packages/pysam/libchtslib.cpython-37m-x86_64-linux-gnu.so)

and i can not get what they mean, so if it possible for you to nicely help me with this, thanks in advance!

Yafei

**Comment by terhorst** [comment]
Are you running smc++ on a different machine than the one you compiled it on?

**Comment by Fengyaa** [comment]
Hi, have you solved this? I met the same error.

**Comment by terhorst** [comment]
@Fengyaa The original poster never responded so I don't know what the issue is. There seem to be some other reports of similar bugs related to this package,for example kundajelab/atac_dnase_pipelines#33. You might try manually reinstalling the `pysam` package.
