### ISSUE TITLE
TypeError: 'numpy.float64' object is not iterable

### ISSUE THREAD

**Issue by baozg** [popgenmethods/smcpp#138]
Hi terhorst,

I am using SMCpp to analyse plant populations, but when I use the split command for one population pairs, it throw `TypeError`. The other seven population pairs have model.json. Here is the detailed command.

Eight population pairs come from five populations,  their sample size are 43,81,56,123,124. The population pairs which cannot run are 43,56. 

Enviroment: smcpp v15.2, CentOS 7

The command I use for eight population pairs:
```bash
# select 10 samples in the population 
# mask bed follow as lh3‘s SNPable
smc++ vcf2smc -d {params.spname} {params.spname} --cores {threads} --mask {input.bed} {input.vcf} {output.smc} {wildcards.chr} {wildcards.pop}:{par    ams.popname}
# estimate for single population
smc++ estimate --cores {threads} --timepoints 0 1e6 --spline cubic --ftol 0.001 -o {params.outdir} 6.5e-9 {params.indir}/{wildcards.pop}.*.smc.gz
#  joint SFS
smc++ vcf2smc --cores {threads} --mask {input.bed} {input.vcf} {output.smc} {wildcards.chr} {wildcards.pop1}:{params.popname1} {wildcards.pop2}:{params.popname2}
# split
smc++ split --cores {threads} --timepoints 0 1e6 --ftol 0.001 -o {params.outdir} {input.model1} {input.model2} {params.indir}/*.smc.gz
```

Error info:
```bash
23148 smcpp.analysis.base INFO theta: 0.000100
23149 smcpp.analysis.base INFO rho: 0.000100
23149 smcpp.data_filter INFO Loading data...
24006 smcpp.data_filter INFO 0.37 Gb of data
24010 smcpp.data_filter INFO 2 populations
24023 smcpp.estimation_tools WARNING Long runs of homozygosity in contig result/10.Demography_history/smcpp/GW_DTU/GW_DTU.Chr4.smc.gz:
[92667 63398] (base pairs)
24039 smcpp.estimation_tools WARNING Long runs of homozygosity in contig result/10.Demography_history/smcpp/GW_DTU/GW_DTU.Chr7.smc.gz:
[79586 58764] (base pairs)
24051 smcpp.estimation_tools WARNING Long runs of homozygosity in contig result/10.Demography_history/smcpp/GW_DTU/GW_DTU.Chr11.smc.gz:
[67283 67327] (base pairs)
320967 smcpp.optimize.plugins.progress_printer INFO Starting EM algorithm...
320968 smcpp.optimize.plugins.progress_printer INFO EM iteration 1 of 1...
320968 smcpp.analysis.base INFO Running E-step
356200 smcpp.analysis.base INFO E-step completed
356202 smcpp.optimize.plugins.loglikelihood_monitor INFO Loglik: -5140641.249029
356217 smcpp.optimize.plugins.parameter_optimizer INFO Updating split, bounds (0.000000, 65.000000)
Traceback (most recent call last):
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/ad/admath/admath.py", line 160, in vectorized_function
    return [vectorized_function(xi, **kwargs) for xi in x]
TypeError: 'numpy.float64' object is not iterable

Traceback (most recent call last):
  File "/data/software/conda_envs/smcpp/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.15.2', 'console_scripts', 'smc++')()
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/smcpp/commands/split.py", line 45, in main
    analysis.run()
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/smcpp/analysis/base.py", line 120, in run
    self._optimizer.run(niter or self._niter)
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/smcpp/optimize/optimizers.py", line 164, in run
    self.update_observers("pre M-step", **kwargs)
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/smcpp/optimize/optimizers.py", line 222, in update_observers
    Observable.update_observers(self, *args, **kwargs)
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/smcpp/observe.py", line 47, in update_observers
    observer.update(*args, **kwargs)
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/smcpp/observe.py", line 18, in wrapper
    wrapped(*args, **kwargs)
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/smcpp/optimize/plugins/parameter_optimizer.py", line 34, in update
    self._f, args=(analysis, tgt, param), method="bounded", bounds=self.bounds
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/scipy/optimize/_minimize.py", line 783, in minimize_scalar
    return _minimize_scalar_bounded(fun, bounds, args, **options)
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 1793, in _minimize_scalar_bounded
    fu = func(x, *args)
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/smcpp/optimize/plugins/parameter_optimizer.py", line 40, in _f
    setattr(tgt, param, x)
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/smcpp/model.py", line 332, in split
    self.update_observers("model update")
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/smcpp/observe.py", line 47, in update_observers
    observer.update(*args, **kwargs)
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/smcpp/observe.py", line 18, in wrapper
    wrapped(*args, **kwargs)
  File "smcpp/_smcpp.pyx", line 366, in smcpp._smcpp.PyTwoPopInferenceManager.update
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/smcpp/model.py", line 210, in stepwise_values
    self(np.cumsum(self.s)),
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/smcpp/model.py", line 187, in __call__
    ret = np.array(ad.admath.exp(self._spline(self._trans(x))))
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/ad/admath/admath.py", line 160, in vectorized_function
    return [vectorized_function(xi, **kwargs) for xi in x]
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/ad/admath/admath.py", line 160, in <listcomp>
    return [vectorized_function(xi, **kwargs) for xi in x]
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/ad/admath/admath.py", line 162, in vectorized_function
    return func(x, **kwargs)
  File "/data/software/conda_envs/smcpp/lib/python3.6/site-packages/ad/admath/admath.py", line 829, in exp
    return math.exp(x.real)
OverflowError: math range error
```

**Comment by baozg** [comment]
It should be inbred related issue

**Comment by mishaploid** [comment]
@terhorst I am also running into this error, the split command works for bootstrapped inputs of the same population, so it seems odd that it's throwing an error. @baozg did you end up finding a solution? The .debug.txt output is attached. 

[debug.txt](https://github.com/popgenmethods/smcpp/files/8188061/debug.txt)

Here is the command (using singularity with the latest docker image): 
```bash
smc++ split --cores 8 -o models/smc_split/LandraceA_ImprovedCultivar/ \
models/smc_estimate_no_timepoints/Landrace_A/model.final.json \
models/smc_estimate_no_timepoints/Improved_Cultivar/model.final.json \
models/smc/input/Landrace_A* models/smc/input/Improved_Cultivar* \
models/smc_split/input/LandraceA_ImprovedCultivar_12* \
models/smc_split/input/LandraceA_ImprovedCultivar_21*
```

The error: 
```bash
Activating singularity image /home/sdturner/carrot-demography/.snakemake/singularity/0bb4573a4ae6de117decd5fcaede26d9.simg
6450 smcpp.analysis.base INFO theta: 0.000100
6451 smcpp.analysis.base INFO rho: 0.000100
6451 smcpp.data_filter INFO Loading data...
70132 smcpp.data_filter INFO 9.15 Gb of data
70238 smcpp.data_filter INFO 2 populations
20360306 smcpp.optimize.plugins.progress_printer INFO Starting EM algorithm...
20360307 smcpp.optimize.plugins.progress_printer INFO EM iteration 1 of 1...
20360307 smcpp.analysis.base INFO Running E-step
21414833 smcpp.analysis.base INFO E-step completed
21414842 smcpp.optimize.plugins.loglikelihood_monitor INFO Loglik: -1949003395.191993
33655476 smcpp.optimize.plugins.parameter_optimizer INFO Updating split, bounds (0.000000, 37.148369)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/ad/admath/admath.py", line 160, in vectorized_function
    return [vectorized_function(xi, **kwargs) for xi in x]
TypeError: 'numpy.float64' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.15.4.dev16+g72ea2e2.d20200621', 'console_scripts', 'smc++')()
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/commands/split.py", line 45, in main
    analysis.run()
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/analysis/base.py", line 120, in run
    self._optimizer.run(niter or self._niter)
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/optimize/optimizers.py", line 164, in run
    self.update_observers("pre M-step", **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/optimize/optimizers.py", line 222, in update_observers
    Observable.update_observers(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/observe.py", line 49, in update_observers
    observer.update(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/observe.py", line 19, in _
    f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/optimize/plugins/parameter_optimizer.py", line 33, in update
    res = scipy.optimize.minimize_scalar(
  File "/usr/lib/python3/dist-packages/scipy/optimize/_minimize.py", line 780, in minimize_scalar
    return _minimize_scalar_bounded(fun, bounds, args, **options)
  File "/usr/lib/python3/dist-packages/scipy/optimize/optimize.py", line 1837, in _minimize_scalar_bounded
    fu = func(x, *args)
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/optimize/plugins/parameter_optimizer.py", line 40, in _f
    setattr(tgt, param, x)
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/model.py", line 327, in split
    self.update_observers("model update")
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/observe.py", line 49, in update_observers
    observer.update(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/observe.py", line 19, in _
    f(self, *args, **kwargs)
  File "smcpp/_smcpp.pyx", line 364, in smcpp._smcpp.PyTwoPopInferenceManager.update
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/model.py", line 205, in stepwise_values
    self(np.cumsum(self.s)),
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/model.py", line 182, in __call__
    ret = np.array(admath.exp(self._spline(self._trans(x))))
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/ad/admath/admath.py", line 160, in vectorized_function
    return [vectorized_function(xi, **kwargs) for xi in x]
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/ad/admath/admath.py", line 160, in <listcomp>
    return [vectorized_function(xi, **kwargs) for xi in x]
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/ad/admath/admath.py", line 162, in vectorized_function
    return func(x, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev16+g72ea2e2.d20200621-py3.8-linux-x86_64.egg/smcpp/ad/admath/admath.py", line 829, in exp
    return math.exp(x.real)
OverflowError: math range error
```
