### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ariloytynoja** [popgenmethods/smcpp#140]
Hi there,
I tried to install the latest version of smc++ from github on Ubuntu linux and always get the same error. The error message is below. Can you see what is going wrong?

Thanks a lot in advance!

Regards, Ari

```
$ smc++
Traceback (most recent call last):
  File "/home/username/.local/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.15.4.dev2+g1823009', 'console_scripts', 'smc++')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2725, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/username/.local/lib/python3.5/site-packages/smcpp-1.15.4.dev2+g1823009-py3.5-linux-x86_64.egg/smcpp/frontend/console.py", line 3, in <module>
    from .. import commands, logging, version, defaults, _smcpp
  File "/home/username/.local/lib/python3.5/site-packages/smcpp-1.15.4.dev2+g1823009-py3.5-linux-x86_64.egg/smcpp/commands/__init__.py", line 1, in <module>
    from . import vcf2smc, estimate, split, chunk, cite, plot, \
  File "/home/username/.local/lib/python3.5/site-packages/smcpp-1.15.4.dev2+g1823009-py3.5-linux-x86_64.egg/smcpp/commands/estimate.py", line 14, in <module>
    from smcpp.analysis.analysis import Analysis
  File "/home/username/.local/lib/python3.5/site-packages/smcpp-1.15.4.dev2+g1823009-py3.5-linux-x86_64.egg/smcpp/analysis/analysis.py", line 7, in <module>
    from .. import estimation_tools, _smcpp, util, logging, spline, data_filter, beta_de
  File "/home/username/.local/lib/python3.5/site-packages/smcpp-1.15.4.dev2+g1823009-py3.5-linux-x86_64.egg/smcpp/estimation_tools.py", line 13, in <module>
    from .contig import Contig
  File "/home/username/.local/lib/python3.5/site-packages/smcpp-1.15.4.dev2+g1823009-py3.5-linux-x86_64.egg/smcpp/contig.py", line 8
    pid: Tuple
       ^
SyntaxError: invalid syntax

```

**Comment by terhorst** [comment]
Hi, SMC++ requires Python 3.7 or later. See https://github.com/popgenmethods/smcpp#build-instructions for more information.
