### ISSUE TITLE
Estimate Error (vcf2smc successful)

### ISSUE THREAD

**Issue by pstokespmb** [popgenmethods/smcpp#151]
Hey @terhorst,

Below you will find the error I encountered when attempting to run estimate. The VCF is the result of post-VQSR improvement and is reasonably high quality. I masked out missing regions using the -mask option during vcf2smc, rather than filling in ./. for missing positions.

I am not sure where the problem stems, but I suspect perhaps it might be from too much masking?

I shared the Drive folder with you (see your email) so you can access the input I used. 

The command I used:
"""""""
smc++ estimate 7.0e-9 --cores 6 -o /global/scratch/peter_stokes/MelisVCFs/estimateOut MelisVCF_Arikara_Chr01.smc.gz MelisVCF_Arikara_Chr02.smc.gz MelisVCF_Arikara_Chr03.smc.gz MelisVCF_Arikara_Chr04.smc.gz MelisVCF_Arikara_Chr05.smc.gz MelisVCF_Arikara_Chr06.smc.gz MelisVCF_Arikara_Chr07.smc.gz MelisVCF_Arikara_Chr08.smc.gz MelisVCF_Arikara_Chr09.smc.gz MelisVCF_Arikara_Chr10.smc.gz MelisVCF_Arikara_Chr11.smc.gz MelisVCF_Arikara_Chr12.smc.gz MelisVCF_Arikara_Chr13.smc.gz MelisVCF_Arikara_Chr14.smc.gz MelisVCF_Arikara_Chr15.smc.gz MelisVCF_Arikara_Chr16.smc.gz MelisVCF_Arikara_Chr17.smc.gz MelisVCF_Hidatsa1_Chr01.smc.gz MelisVCF_Hidatsa1_Chr02.smc.gz MelisVCF_Hidatsa1_Chr03.smc.gz MelisVCF_Hidatsa1_Chr04.smc.gz MelisVCF_Hidatsa1_Chr05.smc.gz MelisVCF_Hidatsa1_Chr06.smc.gz MelisVCF_Hidatsa1_Chr07.smc.gz MelisVCF_Hidatsa1_Chr08.smc.gz MelisVCF_Hidatsa1_Chr09.smc.gz MelisVCF_Hidatsa1_Chr10.smc.gz MelisVCF_Hidatsa1_Chr11.smc.gz MelisVCF_Hidatsa1_Chr12.smc.gz MelisVCF_Hidatsa1_Chr13.smc.gz MelisVCF_Hidatsa1_Chr14.smc.gz MelisVCF_Hidatsa1_Chr15.smc.gz MelisVCF_Hidatsa1_Chr16.smc.gz MelisVCF_Hidatsa1_Chr17.smc.gz MelisVCF_Hopi_mapping_parent_Chr01.smc.gz MelisVCF_Hopi_mapping_parent_Chr02.smc.gz MelisVCF_Hopi_mapping_parent_Chr03.smc.gz MelisVCF_Hopi_mapping_parent_Chr04.smc.gz MelisVCF_Hopi_mapping_parent_Chr05.smc.gz MelisVCF_Hopi_mapping_parent_Chr06.smc.gz MelisVCF_Hopi_mapping_parent_Chr07.smc.gz MelisVCF_Hopi_mapping_parent_Chr08.smc.gz MelisVCF_Hopi_mapping_parent_Chr09.smc.gz MelisVCF_Hopi_mapping_parent_Chr10.smc.gz MelisVCF_Hopi_mapping_parent_Chr11.smc.gz MelisVCF_Hopi_mapping_parent_Chr12.smc.gz MelisVCF_Hopi_mapping_parent_Chr13.smc.gz MelisVCF_Hopi_mapping_parent_Chr14.smc.gz MelisVCF_Hopi_mapping_parent_Chr15.smc.gz MelisVCF_Hopi_mapping_parent_Chr16.smc.gz MelisVCF_Hopi_mapping_parent_Chr17.smc.gz MelisVCF_Mandan1_Chr01.smc.gz MelisVCF_Mandan1_Chr02.smc.gz MelisVCF_Mandan1_Chr03.smc.gz MelisVCF_Mandan1_Chr04.smc.gz MelisVCF_Mandan1_Chr05.smc.gz MelisVCF_Mandan1_Chr06.smc.gz MelisVCF_Mandan1_Chr07.smc.gz MelisVCF_Mandan1_Chr08.smc.gz MelisVCF_Mandan1_Chr09.smc.gz MelisVCF_Mandan1_Chr10.smc.gz MelisVCF_Mandan1_Chr11.smc.gz MelisVCF_Mandan1_Chr12.smc.gz MelisVCF_Mandan1_Chr13.smc.gz MelisVCF_Mandan1_Chr14.smc.gz MelisVCF_Mandan1_Chr15.smc.gz MelisVCF_Mandan1_Chr16.smc.gz MelisVCF_Mandan1_Chr17.smc.gz

"""""""

The error I received before I killed the run:

"""""""
5183 smcpp.analysis.base INFO theta: 0.000100
5183 smcpp.analysis.base INFO rho: 0.000100
5184 smcpp.data_filter INFO Loading data...
104361 smcpp.data_filter INFO 12.18 Gb of data
104382 smcpp.data_filter INFO 1 population
--- Logging error ---
Traceback (most recent call last):
  File "/global/software/sl-7.x86_64/modules/langs/python/3.7/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/global/software/sl-7.x86_64/modules/langs/python/3.7/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/global/software/sl-7.x86_64/modules/langs/python/3.7/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/global/software/sl-7.x86_64/modules/langs/python/3.7/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
  File "/global/home/groups/consultsw/sl-7.x86_64/modules/smcpp/1.15.3/lib/python3.7/site-packages/numpy/ma/core.py", line 4344, in __int__
    raise MaskError('Cannot convert masked element to a Python int.')
numpy.ma.core.MaskError: Cannot convert masked element to a Python int.
Call stack:
  File "/global/home/groups/consultsw/sl-7.x86_64/modules/smcpp/1.15.3/bin/smc++", line 10, in <module>
    sys.exit(main())
  File "/global/home/groups/consultsw/sl-7.x86_64/modules/smcpp/1.15.3/lib/python3.7/site-packages/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/global/home/groups/consultsw/sl-7.x86_64/modules/smcpp/1.15.3/lib/python3.7/site-packages/smcpp/commands/estimate.py", line 47, in main
    analysis = Analysis(args.data, args)
  File "/global/home/groups/consultsw/sl-7.x86_64/modules/smcpp/1.15.3/lib/python3.7/site-packages/smcpp/analysis/analysis.py", line 23, in __init__
    if self.npop != 1:
  File "/global/home/groups/consultsw/sl-7.x86_64/modules/smcpp/1.15.3/lib/python3.7/site-packages/smcpp/analysis/base.py", line 183, in npop
    return len(self.populations)
  File "/global/home/groups/consultsw/sl-7.x86_64/modules/smcpp/1.15.3/lib/python3.7/site-packages/smcpp/analysis/base.py", line 71, in populations
    return self._pipeline["load_data"].populations
  File "/global/home/groups/consultsw/sl-7.x86_64/modules/smcpp/1.15.3/lib/python3.7/site-packages/smcpp/data_filter.py", line 33, in __getitem__
    self.run()
  File "/global/home/groups/consultsw/sl-7.x86_64/modules/smcpp/1.15.3/lib/python3.7/site-packages/smcpp/data_filter.py", line 53, in run
    self._results = f(self._results)
  File "/global/home/groups/consultsw/sl-7.x86_64/modules/smcpp/1.15.3/lib/python3.7/site-packages/smcpp/data_filter.py", line 22, in __call__
    return self.run(contigs)
  File "/global/home/groups/consultsw/sl-7.x86_64/modules/smcpp/1.15.3/lib/python3.7/site-packages/smcpp/data_filter.py", line 229, in run
    "mutation counts in %dbp windows: min=%d .05=%d .95=%d max=%d", self.w, *res
Message: 'mutation counts in %dbp windows: min=%d .05=%d .95=%d max=%d'
Arguments: (142857, masked, masked, masked, masked)
^C265624 smcpp._smcpp:src/inference_manager.cpp:250 CRITICAL Aborting

"""""""

**Comment by DeondeJager** [comment]
Hi again @pstokespmb :)

Have you by any chance solved this error? I'm getting the same error message masking sites not in the VCF with -mask. I'm using Python 3.7 as required.

**Comment by pengyan19** [comment]
hello，I also meet this question，Do you solved it?

**Comment by Apis-DeLorian** [comment]
I also am getting this error on some contigs that I run this on with -mask, but not others. @terhorst Does this mean the that the mask.bed is not actually being applied? Thank you.

**Comment by huangl07** [comment]
is anyone fix this error?

**Comment by grahamgower** [comment]
I'm seeing this same error, running `smc++ estimate` on data without any masking applied. This has nothing to do with vcf2smc's `--mask` option, but rather is talking about numpy's support for so-called "masked arrays".
```
numpy.ma.core.MaskError: Cannot convert masked element to a Python int.
```

The relevant code triggering this is just used for debug logging.
https://github.com/popgenmethods/smcpp/blob/7bc166841b1e3fabd364df576878766a16710704/smcpp/data_filter.py#L228-L231

Looking at the code above it, the `mc` variable is just a regular numpy array, not a masked array, so using `scipy.stats.mstats.mquantile()` seems unnecessary here. Using `np.quantile()` ought to fix this.
