### ISSUE TITLE
Missing package dependency list in README

### ISSUE THREAD

**Issue by lczech** [popgenmethods/smcpp#162]
When compiling from source, the README lacks a few details that were hard to figure out:

- When running `python setup.py install`, it should be mentioned that `numpy` and `cython` are required.
- Furthermore, `python3.7-dev` needs to be installed on the system, which should be mentioned.
- Although the requirements state that Python 3.7 is needed, I first had an older Python version active when running `python setup.py install`. My mistake, but mentioning this requirement at that point might help.

**Comment by terhorst** [comment]
`numpy` is already listed as an install dependency, and `cython` as a build dependency, in `setup.py`. If you do not have them installed, the installer should inform you of this fact. Regarding the other error, can you elaborate on what happened? This is the first time I'm hearing of the `Pillow` package, and SMC++ does not use it directly. To the best of my knowledge, all of the packages that SMC++ directly depends on are listed in `setup.py`. If that package was missing it's because the setuptools dependency resolver failed get it for some reason.

**Comment by lczech** [comment]
> numpy is already listed as an install dependency, and cython as a build dependency, in setup.py. If you do not have them installed, the installer should inform you of this fact.

That's right, and works well enough. I just thought that as there is already a list of required libraries in the readme, these might be worth mentioning there as well ;-)

> This is the first time I'm hearing of the Pillow package, and SMC++ does not use it directly.

When running `$ smc++`, the full error message I got is:
```
Traceback (most recent call last):
  File "/usr/local/bin/smc++", line 33, in <module>
    sys.exit(load_entry_point('smcpp==1.15.4.dev5+g94b7266', 'console_scripts', 'smc++')())
  File "/usr/local/bin/smc++", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/lczech/.local/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 96, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/smcpp-1.15.4.dev5+g94b7266-py3.7-linux-x86_64.egg/smcpp/frontend/console.py", line 3, in <module>
    from .. import commands, logging, version, defaults, _smcpp
  File "/usr/local/lib/python3.7/dist-packages/smcpp-1.15.4.dev5+g94b7266-py3.7-linux-x86_64.egg/smcpp/commands/__init__.py", line 1, in <module>
    from . import vcf2smc, estimate, split, chunk, cite, plot, \
  File "/usr/local/lib/python3.7/dist-packages/smcpp-1.15.4.dev5+g94b7266-py3.7-linux-x86_64.egg/smcpp/commands/plot.py", line 9, in <module>
    from .. import util, plotting, model
  File "/usr/local/lib/python3.7/dist-packages/smcpp-1.15.4.dev5+g94b7266-py3.7-linux-x86_64.egg/smcpp/plotting.py", line 5, in <module>
    matplotlib.use("Agg")
  File "/home/lczech/.local/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/home/lczech/.local/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/home/lczech/.local/lib/python3.7/site-packages/matplotlib/__init__.py", line 1280, in use
    from matplotlib import pyplot as plt
  File "/home/lczech/.local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2282, in <module>
    switch_backend(rcParams["backend"])
  File "/home/lczech/.local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 221, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/lczech/.local/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 50, in <module>
    from PIL import Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
```
which I solved [according to this thread](https://stackoverflow.com/q/25340698) by `sudo apt-get install python-pillow`.

Judging from the message, it seems that this is related to matplotlib. My system is Ubuntu 18.04.
