### ISSUE TITLE
can't install v1.15.3 with conda

### ISSUE THREAD

**Issue by kevin-furant** [popgenmethods/smcpp#169]
when i installed smc++ with conda ,like this:
#########################################
conda install -c terhorst smcpp=1.15.3
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                   

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
################################################
if i use command like conda install -c terhorst smcpp .it will install v1.3.8,but this version can't work well 
`cat smc++`
#!/TJPROJ2/COG/software/Miniconda3_fxk/envs/smc/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'smcpp==1.3.9.dev2+ng00dfb92.d20170111','console_scripts','smc++'
__requires__ = 'smcpp==1.3.9.dev2+ng00dfb92.d20170111'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('smcpp==1.3.9.dev2+ng00dfb92.d20170111', 'console_scripts', 'smc++')()
    )
##########################################
log like this :
Traceback (most recent call last):
  File "/TJPROJ2/COG/software/Miniconda3_fxk/envs/smc/bin/smc++", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/TJPROJ2/COG/software/Miniconda3_fxk/envs/smc/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3267, in <module>
    @_call_aside
  File "/TJPROJ2/COG/software/Miniconda3_fxk/envs/smc/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in _call_aside
    f(*args, **kwargs)
  File "/TJPROJ2/COG/software/Miniconda3_fxk/envs/smc/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3280, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/TJPROJ2/COG/software/Miniconda3_fxk/envs/smc/lib/python3.7/site-packages/pkg_resources/__init__.py", line 582, in _build_master
    ws.require(__requires__)
  File "/TJPROJ2/COG/software/Miniconda3_fxk/envs/smc/lib/python3.7/site-packages/pkg_resources/__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/TJPROJ2/COG/software/Miniconda3_fxk/envs/smc/lib/python3.7/site-packages/pkg_resources/__init__.py", line 785, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'smcpp==1.3.9.dev2+ng00dfb92.d20170111' distribution was not found and is required by the application
#################################
should conda can install smc++?

**Comment by terhorst** [comment]
For exactly this reason (see #164) I'm no longer able to support Anaconda. The preferred way to use the program is now via Docker: https://github.com/popgenmethods/smcpp#installation-instructions. Thanks!

**Comment by kevin-furant** [comment]
> 
> 
> For exactly this reason (see #164) I'm no longer able to support Anaconda. The preferred way to use the program is now via Docker: https://github.com/popgenmethods/smcpp#installation-instructions. Thanks!

ok，thank you!

**Comment by kevin-furant** [comment]
> 
> 
> For exactly this reason (see #164) I'm no longer able to support Anaconda. The preferred way to use the program is now via Docker: https://github.com/popgenmethods/smcpp#installation-instructions. Thanks!

hello Jonathan
       i use udocker to run smc++   but it throw a error .
##########################################
udocker images
REPOSITORY
terhorst/smcpp:latest

my command line:
udocker run --rm -v $PWD/AL:/mnt terhorst/smcpp:latest estimate -o AL/ 7.0e-09 AL/*.smc.gz

Error: command not found or has no execute bit set:  [u'/usr/local/bin/smc++', 'estimate', '-o', 'AL/', '7.0e-09', 'AL/megascaffold_10.smc.gz', 'AL/megascaffold_1.smc.gz', 'AL/megascaffold_2.smc.gz', 'AL/megascaffold_3.smc.gz', 'AL/megascaffold_5.smc.gz', 'AL/megascaffold_6.smc.gz', 'AL/megascaffold_7.smc.gz', 'AL/megascaffold_8.smc.gz']
###########################################
i don't kown why the command can't be found? i have pull the image to local.

**Comment by terhorst** [comment]
Sorry, but I've only ever tested it with Docker, which I verified runs your command correctly. It seems this might be indigo-dc/udocker#196.

**Comment by kevin-furant** [comment]
the problem should be udocker, thank you all the same,i will try it with docker later.
