### ISSUE TITLE
Can not find some pysam package init files when I install smcpp

### ISSUE THREAD

**Issue by lilei1** [popgenmethods/smcpp#17]
Hi, I have such kind of errors when I installed the program in OX X EI Capitan with the commandline " CC=gcc-6 CXX=g++-6 python setup.py install".
The errors are like this:
```
Installed /Users/lilei/anaconda/lib/python3.6/site-packages/smcpp-1.8.0-py3.6-macosx-10.7-x86_64.egg
Processing dependencies for smcpp==1.8.0
Searching for pysam>=0.9
Reading https://pypi.python.org/simple/pysam/
Downloading https://pypi.python.org/packages/87/8e/d2d8238558970df37c7aa01ddec63057a98042334e939b4c1c69cb9a2504/pysam-0.10.0.tar.gz#md5=a1f3333ce60f8de542624cb07c792fc0
Best match: pysam 0.10.0
Processing pysam-0.10.0.tar.gz
Writing /var/folders/v2/9cf1kspn6250q1nt3sl0bx7h0000gn/T/easy_install-0c7yq7wr/pysam-0.10.0/setup.cfg
Running pysam-0.10.0/setup.py -q bdist_egg --dist-dir /var/folders/v2/9cf1kspn6250q1nt3sl0bx7h0000gn/T/easy_install-0c7yq7wr/pysam-0.10.0/egg-dist-tmp-6hq1ghc9
# pysam: cython is available - using cythonize if necessary
# pysam: htslib mode is shared
# pysam: HTSLIB_CONFIGURE_OPTIONS=None
checking for gcc... gcc-6
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc-6 accepts -g... yes
checking for gcc-6 option to accept ISO C89... none needed
checking for ranlib... ranlib
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking how to run the C preprocessor... gcc-6 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for gmtime_r... yes
checking for zlib.h... yes
checking for inflate in -lz... yes
checking for curl_easy_pause in -lcurl... yes
checking for CCHmac... yes
configure: creating ./config.status
config.status: creating config.mk
config.status: creating config.h
# pysam: htslib configure options: --enable-libcurl
# pysam: htslib_config LDFLAGS=
# pysam: htslib_config LIBHTS_OBJS=kfunc.o knetfile.o kstring.o bgzf.o faidx.o hfile.o hfile_net.o hts.o md5.o regidx.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_external.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/sam_header.o cram/string_alloc.o cram/thread_pool.o cram/vlen.o cram/zfio.o hfile_libcurl.o
# pysam: htslib_config LIBS=-lcurl
# pysam: htslib_config PLATFORM=Darwin
# pysam: config_option: ENABLE_PLUGINS=0
# pysam: config_option: HAVE_COMMONCRYPTO=1
# pysam: config_option: HAVE_GMTIME_R=1
# pysam: config_option: HAVE_HMAC=0
# pysam: config_option: HAVE_IRODS=0
# pysam: config_option: HAVE_LIBCURL=1
# pysam: config_option: HAVE_MMAP=1
package init file 'samtools/__init__.py' not found (or not a regular file)
package init file 'bcftools/__init__.py' not found (or not a regular file)
package init file 'samtools/win32/__init__.py' not found (or not a regular file)
package init file 'htslib/__init__.py' not found (or not a regular file)
package init file 'htslib/htslib/__init__.py' not found (or not a regular file)
warning: no files found matching 'KNOWN_BUGS'
warning: no files found matching 'THANKS'
warning: no files found matching 'pysam/c*.pxd'
warning: no files found matching 'pysam/c*.pyx'
warning: no files found matching 'pysam/c*.c'
warning: no files found matching 'samtools/configure'
warning: no files found matching 'samtools/config.mk.in'
warning: no files found matching 'samtools/config.h.in'
warning: no files found matching 'tests/pysam_data'
warning: no files found matching 'tests/tabix_data'
Traceback (most recent call last):
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:5261)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2253, in visit_StatListNode
    if not self.current_directives['remove_unreachable']:
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 156, in save_modules
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 197, in setup_context
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 246, in run_setup
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 276, in run
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 245, in runner
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 47, in _execfile
  File "/var/folders/v2/9cf1kspn6250q1nt3sl0bx7h0000gn/T/easy_install-0c7yq7wr/pysam-0.10.0/setup.py", line 551, in <module>
  File "/Users/lilei/anaconda/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/lilei/anaconda/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/lilei/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/bdist_egg.py", line 161, in run
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/bdist_egg.py", line 147, in call_command
  File "/Users/lilei/anaconda/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/lilei/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/install_lib.py", line 11, in run
  File "/Users/lilei/anaconda/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/Users/lilei/anaconda/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/lilei/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/Users/lilei/anaconda/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 192, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 345, in cython_sources
    full_module_name=module_name)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 684, in compile
    return compile_single(source, options, full_module_name)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 634, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 494, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 340, in run_pipeline
    data = phase(data)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 33, in parse
    scope = context.find_module(full_module_name, pos = initial_pos, need_pxd = 0)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 221, in find_module
    err, result = self.process_pxd(source_desc, scope, qualified_name)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 135, in process_pxd
    result = Pipeline.run_pipeline(pipeline, source_desc)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 340, in run_pipeline
    data = phase(data)
  File "Cython/Compiler/Visitor.py", line 286, in Cython.Compiler.Visitor.CythonTransform.__call__ (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:7423)
  File "Cython/Compiler/Visitor.py", line 269, in Cython.Compiler.Visitor.VisitorTransform.__call__ (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:7095)
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:5339)
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:5281)
  File "Cython/Compiler/Visitor.py", line 296, in Cython.Compiler.Visitor.CythonTransform.visit_Node (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:7629)
  File "Cython/Compiler/Visitor.py", line 247, in Cython.Compiler.Visitor.VisitorTransform.visitchildren (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:6414)
  File "Cython/Compiler/Visitor.py", line 247, in Cython.Compiler.Visitor.VisitorTransform.visitchildren (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:6846)
  File "Cython/Compiler/Visitor.py", line 248, in Cython.Compiler.Visitor.VisitorTransform.visitchildren (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:6434)
  File "Cython/Compiler/Visitor.py", line 221, in Cython.Compiler.Visitor.TreeVisitor._visitchildren (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:6117)
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:5602)
  File "Cython/Compiler/Visitor.py", line 188, in Cython.Compiler.Visitor.TreeVisitor._visit (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:5483)
  File "Cython/Compiler/Visitor.py", line 147, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:4489)
Cython.Compiler.Errors.CompilerCrash: 
Error compiling Cython file:
------------------------------------------------------------
...
from libc.stdint cimport int8_t, int16_t, int32_t, int64_t
^
------------------------------------------------------------

pysam/libchtslib.pxd:1:0: Compiler crash in RemoveUnreachableCode

ModuleNode.body = StatListNode(libchtslib.pxd:1:0)

Compiler crash traceback from this point on:
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:5261)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2253, in visit_StatListNode
    if not self.current_directives['remove_unreachable']:
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 62, in <module>
    'console_scripts': ['smc++ = smcpp.frontend.console:main'],
  File "/Users/lilei/anaconda/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/lilei/anaconda/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/lilei/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/install.py", line 67, in run
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/install.py", line 117, in do_egg_install
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 409, in run
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 645, in easy_install
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 696, in install_item
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 741, in process_distribution
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 851, in resolve
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1123, in best_match
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1135, in obtain
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 664, in easy_install
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 694, in install_item
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 875, in install_eggs
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 1114, in build_and_install
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/easy_install.py", line 1100, in run_setup
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 249, in run_setup
  File "/Users/lilei/anaconda/lib/python3.6/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 197, in setup_context
  File "/Users/lilei/anaconda/lib/python3.6/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 168, in save_modules
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 143, in resume
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 156, in save_modules
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 197, in setup_context
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 246, in run_setup
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 276, in run
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 245, in runner
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/sandbox.py", line 47, in _execfile
  File "/var/folders/v2/9cf1kspn6250q1nt3sl0bx7h0000gn/T/easy_install-0c7yq7wr/pysam-0.10.0/setup.py", line 551, in <module>
  File "/Users/lilei/anaconda/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/lilei/anaconda/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/lilei/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/bdist_egg.py", line 161, in run
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/bdist_egg.py", line 147, in call_command
  File "/Users/lilei/anaconda/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/lilei/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/install_lib.py", line 11, in run
  File "/Users/lilei/anaconda/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/Users/lilei/anaconda/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/lilei/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/Users/lilei/anaconda/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 192, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 345, in cython_sources
    full_module_name=module_name)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 684, in compile
    return compile_single(source, options, full_module_name)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 634, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 494, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 340, in run_pipeline
    data = phase(data)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 33, in parse
    scope = context.find_module(full_module_name, pos = initial_pos, need_pxd = 0)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 221, in find_module
    err, result = self.process_pxd(source_desc, scope, qualified_name)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 135, in process_pxd
    result = Pipeline.run_pipeline(pipeline, source_desc)
  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/Pipeline.py", line 340, in run_pipeline
    data = phase(data)
  File "Cython/Compiler/Visitor.py", line 286, in Cython.Compiler.Visitor.CythonTransform.__call__ (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:7423)
  File "Cython/Compiler/Visitor.py", line 269, in Cython.Compiler.Visitor.VisitorTransform.__call__ (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:7095)
  File "Cython/Compiler/Visitor.py", line 182, in Cython.Compiler.Visitor.TreeVisitor._visit (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:5339)
  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:5281)
  File "Cython/Compiler/Visitor.py", line 296, in Cython.Compiler.Visitor.CythonTransform.visit_Node (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:7629)
  File "Cython/Compiler/Visitor.py", line 247, in Cython.Compiler.Visitor.VisitorTransform.visitchildren (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:6414)
  File "Cython/Compiler/Visitor.py", line 247, in Cython.Compiler.Visitor.VisitorTransform.visitchildren (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:6846)
  File "Cython/Compiler/Visitor.py", line 248, in Cython.Compiler.Visitor.VisitorTransform.visitchildren (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:6434)
  File "Cython/Compiler/Visitor.py", line 221, in Cython.Compiler.Visitor.TreeVisitor._visitchildren (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:6117)
  File "Cython/Compiler/Visitor.py", line 193, in Cython.Compiler.Visitor.TreeVisitor._visitchild (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:5602)
  File "Cython/Compiler/Visitor.py", line 188, in Cython.Compiler.Visitor.TreeVisitor._visit (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:5483)
  File "Cython/Compiler/Visitor.py", line 147, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:4489)
setuptools.sandbox.UnpickleableException: CompilerCrash((<FileSourceDescriptor:/private/var/folders/v2/9cf1kspn6250q1nt3sl0bx7h0000gn/T/easy_install-0c7yq7wr/pysam-0.10.0/pysam/libchtslib.pxd>, 1, 0), 'RemoveUnreachableCode', 'Compiler crash in RemoveUnreachableCode\n\nModuleNode.body = StatListNode(libchtslib.pxd:1:0)\n\nCompiler crash traceback from this point on:\n  File "Cython/Compiler/Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit (/Users/ilan/minonda/conda-bld/cython_1482522032589/work/Cython-0.25.2/Cython/Compiler/Visitor.c:5261)\n  File "/Users/lilei/anaconda/lib/python3.6/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2253, in visit_StatListNode\n    if not self.current_directives[\'remove_unreachable\']:\nTypeError: \'NoneType\' object is not subscriptable', TypeError("'NoneType' object is not subscriptable",), <traceback object at 0x115c48b88>)
```

**Comment by terhorst** [comment]
``pysam`` appears to have a ton of issues related to building using ``pip`` (try [Googling "pysam build error"](https://www.google.com/search?q=pysam+build+error). I have worked around this in the past by running ``pip install pysam`` before running ``setup.py``.
