### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by mlaylwar** [popgenmethods/smcpp#180]
Hi,

I am running vcf2smc and am receiving the error 'tuple index out of range'. I know that previously it has been mentioned that this may be caused by missing genotypes being coded as "." rather than "./.". However, in my vcf file any missing genotypes are coded as "./.". Do you have any idea what else could be causing this issue?

Many thanks,
Megan

The full error output is as follows:

Traceback (most recent call last):
  File "/softwares/python383/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.15.4.dev17+g2ef0edb', 'console_scripts', 'smc++')()
  File "/softwares/python383/lib/python3.8/site-packages/smcpp-1.15.4.dev17+g2ef0edb-py3.8-linux-x86_64.egg/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/softwares/python383/lib/python3.8/site-packages/smcpp-1.15.4.dev17+g2ef0edb-py3.8-linux-x86_64.egg/smcpp/commands/vcf2smc.py", line 255, in main
    abnb = rec2gt(rec)
  File "/softwares/python383/lib/python3.8/site-packages/smcpp-1.15.4.dev17+g2ef0edb-py3.8-linux-x86_64.egg/smcpp/commands/vcf2smc.py", line 170, in rec2gt
    bs = [[rec.samples[d].alleles[i] != ref
  File "/softwares/python383/lib/python3.8/site-packages/smcpp-1.15.4.dev17+g2ef0edb-py3.8-linux-x86_64.egg/smcpp/commands/vcf2smc.py", line 170, in <listcomp>
    bs = [[rec.samples[d].alleles[i] != ref
  File "/softwares/python383/lib/python3.8/site-packages/smcpp-1.15.4.dev17+g2ef0edb-py3.8-linux-x86_64.egg/smcpp/commands/vcf2smc.py", line 172, in <listcomp>
    if rec.samples[d].alleles[i] is not None]
IndexError: tuple index out of range

**Comment by XiaXiaTianTian** [comment]
Has anyone solved this issue?

Thanks a lot.

Xia

**Comment by zhaodz980805-cpu** [comment]
Hello, I also encountered this problem recently. Has anyone solved it? I look forward to anyone's reply very much, thank you very much!
