### ISSUE TITLE
SMC++ extimate OSError

### ISSUE THREAD

**Issue by zhangzb554** [popgenmethods/smcpp#223]
Hi, I have a problem when running smc++ on version 1.15.5.
I run vcf2smc with the following command using the example data:
smc++ vcf2smc example.vcf.gz smc_out/test.smc.gz 1 pop1:msp_0,msp_1,msp_2,msp_3,msp_4

The above command works correctly. However, when I run 'smc++ estimate 1e-9 ./smc_out/test.smc.gz', the error occurred:
1169 smcpp.analysis.base INFO theta: 0.000100
1170 smcpp.analysis.base INFO rho: 0.000100
1170 smcpp.data_filter INFO Loading data...
1448 smcpp.data_filter INFO 0.00 Gb of data
1449 smcpp.data_filter INFO 1 population
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zhibin/anaconda3/lib/python3.8/multiprocessing/forkserver.py", line 207, in main
    with socket.socket(socket.AF_UNIX, fileno=listener_fd) as listener, \
  File "/home/zhibin/anaconda3/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/home/zhibin/anaconda3/bin/smc++", line 33, in <module>
    sys.exit(load_entry_point('smcpp==0.0.0', 'console_scripts', 'smc++')())
  File "/home/zhibin/anaconda3/lib/python3.8/site-packages/smcpp-0.0.0-py3.8-linux-x86_64.egg/smcpp/frontend/console.py", line 28, in main
    cmds[args.command].main(args)
  File "/home/zhibin/anaconda3/lib/python3.8/site-packages/smcpp-0.0.0-py3.8-linux-x86_64.egg/smcpp/commands/estimate.py", line 47, in main
    analysis = Analysis(args.data, args)
  File "/home/zhibin/anaconda3/lib/python3.8/site-packages/smcpp-0.0.0-py3.8-linux-x86_64.egg/smcpp/analysis/analysis.py", line 24, in __init__
    if self.npop != 1:
  File "/home/zhibin/anaconda3/lib/python3.8/site-packages/smcpp-0.0.0-py3.8-linux-x86_64.egg/smcpp/analysis/base.py", line 184, in npop
    return len(self.populations)
  File "/home/zhibin/anaconda3/lib/python3.8/site-packages/smcpp-0.0.0-py3.8-linux-x86_64.egg/smcpp/analysis/base.py", line 72, in populations
    return self._pipeline["load_data"].populations
  File "/home/zhibin/anaconda3/lib/python3.8/site-packages/smcpp-0.0.0-py3.8-linux-x86_64.egg/smcpp/data_filter.py", line 34, in __getitem__
    self.run()
  File "/home/zhibin/anaconda3/lib/python3.8/site-packages/smcpp-0.0.0-py3.8-linux-x86_64.egg/smcpp/data_filter.py", line 54, in run
    self._results = f(self._results)
  File "/home/zhibin/anaconda3/lib/python3.8/site-packages/smcpp-0.0.0-py3.8-linux-x86_64.egg/smcpp/data_filter.py", line 77, in __call__
    with self.Pool() as p:
  File "/home/zhibin/anaconda3/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/home/zhibin/anaconda3/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/home/zhibin/anaconda3/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/home/zhibin/anaconda3/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/home/zhibin/anaconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/zhibin/anaconda3/lib/python3.8/multiprocessing/context.py", line 290, in _Popen
    return Popen(process_obj)
  File "/home/zhibin/anaconda3/lib/python3.8/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/home/zhibin/anaconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/zhibin/anaconda3/lib/python3.8/multiprocessing/popen_forkserver.py", line 59, in _launch
    self.pid = forkserver.read_signed(self.sentinel)
  File "/home/zhibin/anaconda3/lib/python3.8/multiprocessing/forkserver.py", line 334, in read_signed
    raise EOFError('unexpected EOF')
EOFError: unexpected EOF

The same problem occurs with my real data. Could you please give me some advice to fix it? Thanks a lot!

**Comment by Risingsun93** [comment]
@zhangzb554 how to solve this error please help
