### ISSUE TITLE
ValueError: invalid file `b'smc.sorted.recode.vcf.gz'` (mode=`b'r'`) - is it VCF/BCF format

### ISSUE THREAD

**Issue by lnqiao** [popgenmethods/smcpp#229]
When I run smc++ vcf2smc, it was mistaken as follows :
 docker run --rm -v $PWD:/mnt terhorst/smcpp:latest vcf2smc smc.sorted.recode.vcf.gz  try_chr.gz Chr1  SG:D382,D397
708 smcpp.commands.vcf2smc WARNING Neither missing cutoff (-c) or mask (-m) has been specified. This means that stretches of the chromosome that do not have any VCF entries (for example, centromeres) will be interpreted as homozygous recessive.
708 smcpp.commands.vcf2smc INFO Population 1:
708 smcpp.commands.vcf2smc INFO Distinguished lineages: D382:0, D382:1
708 smcpp.commands.vcf2smc INFO Undistinguished lineages: D397:0, D397:1
Traceback (most recent call last):
  File "/usr/local/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.15.4.dev18+gca077da.d20210316', 'console_scripts', 'smc++')()
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev18+gca077da.d20210316-py3.8-linux-x86_64.egg/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev18+gca077da.d20210316-py3.8-linux-x86_64.egg/smcpp/commands/vcf2smc.py", line 128, in main
    vcf = VariantFile(args.vcf)
  File "pysam/libcbcf.pyx", line 4036, in pysam.libcbcf.VariantFile.__init__
  File "pysam/libcbcf.pyx", line 4266, in pysam.libcbcf.VariantFile.open
ValueError: invalid file `b'smc.sorted.recode.vcf.gz'` (mode=`b'r'`) - is it VCF/BCF format?

my vcfformat is as follows ：
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  D365    D366    D367    D369    D370    D371    D372    D373    D374    D375    D376    D377    D378    D379    D380    D382    D383    D384       D385    D386    D387    D388    D389    D390    D391    D392    D393    D394    D395    D396    D397    D398    D399    D400    D401    D402    D403    D404    D405    D406    D407    D408    D409    D410       D411    D412    D413    D414    D416    D417    D418    D419    D420    D421    D422    D423    D424    D425    D426    D427    D428    D429    D430    D431    D432    D433    D434    D435    D436    D437       D438    D439    D440    D441    D442    D443    D444    D445    D446    D447    D448    D449    D451    D452    D453    D454    D455    D456    D457    D458    D459    D460    D461    D462    D463    D464       D465    D466    D467    D468    D469    D470    D471    D472    D473    D474    D475    D476    D477    D478    D479    D480    D481    D482    D483    D484    D485    D486    D487    D488    D489    D490       D491    D492    D493    D494    D495    D496    D497    D498    D499    D500    D501    D502    D503    D504    D505    D506    D507    D508    D509    D510    D511    D512    D513    D514    D515    D516       D517    D518    D519    D520    D521    D522    D523    D524    D525    D526    D527    D528    D529    D530    D531    D532    D533    D534    D535    D536    D537    D538    D539    D540    D541    D542       D543    D544    D545    D546    D547    D548    D549    D550    D551    D552    D553    D554    D555    D556    D557    D558    D559    D560    D561    D562    D563    D564    D565    D566    D567    D568       D569    D570    D571    D572    D573    D574    D575    D576    D577    D578    D579    D580    D581    D582    D583    D584    D585    D586    D587    D588    D589    D590    D591    D592    D593    D594       D595    D596    D597    D598    D599    D600    D601    D602    D603    D604    D605    D606    D607    D608    D609    D610    D611    D612    D613    D614    D615    D616    D617    D618    D619    D620       D621    D622    D623    D624    D625    D626    D627    D628    D629    D630    D631    D632    D633    D634    D635    D636    D637    D638    D639    D640    D641    D642    D643    D644    D645    D646       D647    D648    D650    D651    D652    D653    D655    D656    D659    D661    D662    D663    D664    D665    D666    D667    D669    D670    D673    D674    D680    D681    D682    D685    D687    D688       D689    D690    D691    D692    D693    D694    D695    D696    D697    D698    D699    D700    D701    D702    D703    D704    D705    D706    D707    D708    D709    D710    D711    D712    D713    D714       D715    D716    D717    D718    D719    D720    D721    D722    D723    D724    D725    D726    D727    D728
Chr01   143049  Chr01__143049   A       G       2346.22 PASS    .       GT:AD:DP:GQ:PL  ./.:0,0:0:.:0,0,0       0/1:3,2:5:34:34,0,110   0/0:6,0:6:18:0,18,161   0/1:10,2:12:13:13,0,262 0/1:3,4:8:78:78,0,104   0/0:7,0:7:6:0,6,223        0/0:6,0:6:0:0,0,118     0/0:7,0:7:0:0,0,104     0/0:8,0:8:0:0,0,175     0/0:9,0:9:0:0,0,170     0/0:8,0:8:0:0,0,236     0/0:5,0:5:15:0,15,182   0/0:4,0:4:9:0,9,135     0/0:13,0:13:39:0,39,466    0/0:7,0:7:0:0,0,113     0/0:6,0:6:18:0,18,186   0/0:4,0:4:12:0,12,141   0/0:13,0:13:23:0,23,379 0/0:6,0:6:15:0,15,225   ./.:0,0:0:.:0,0,0       0/0:4,0:4:0:0,0,84      0/0:10,0:10:30:0,30,258 0/0:2,0:2:6:0,6,57 0/0:5,0:5:15:0,15,182   0/1:3,2:5:75:75,0,120   0/0:4,0:4:0:0,0,96      0/0:11,0:11:33:0,33,423 ./.:0,0:0:.:0,0,0       0/1:1,3:4:30:62,0,30    0/0:1,0:1:3:0,3,30      0/1:10,2:12:14:14,0,257 0/0:9,0:9:0:0,0,215        0/0:11,0:11:18:0,18,356 0/1:3,2:5:34:34,0,104   0/1:10,2:13:14:14,0,338 0/0:7,0:7:0:0,0,166     0/0:5,0:5:15:0,15,182   0/0:1,0:1:3:0,3,30      0/0:5,0:5:15:0,15,156   0/0:12,0:12:33:0,33,495 0/0:8,0:8:18:0,18,270      0/0:9,0:9:24:0,24,360   0/0:22,0:22:49:0,49,759 0/0:10,0:10:14:0,14,322 0/0:4,0:4:12:0,12,114   0/0:2,0:2:6:0,6,57      0/0:3,0:3:9:0,9,91      0/0:9,0:9:27:0,27,311   0/0:11,0:11:17:0,17,318    0/0:13,0:13:36:0,36,540 0/0:8,0:8:0:0,0,159     0/0:7,0:7:21:0,21,228   0/0:6,0:6:18:0,18,224   0/0:21,0:21:23:0,23,518 0/0:8,0:8:24:0,24,291   0/1:11,2:14:10:10,0,391 0/0:11,0:11:0:0,0,302   0/1:13,2:15:4:4,0,403      0/0:8,0:8:24:0,24,264   0/0:5,0:5:15:0,15,182   0/0:19,0:19:7:0,7,582   0/0:9,0:9:27:0,27,323   0/0:12,0:12:5:0,5,341   0/0:8,0:8:9:0,9,277     0/0:7,0:7:18:0,18,270   0/0:7,0:7:5:0,5,182     0/1:8,2:11:20:20,0,246     0/0:12,0:12:36:0,36,368 0/0:10,0:10:30:0,30,357 0/0:5,0:5:0:0,0,152     1/1:0,1:1:3:45,3,0      0/1:6,2:9:26:26,0,163   0/0:14,0:14:39:0,39,585 0/0:6,0:6:18:0,18,239   0/1:6,2:9:25:25,0,189      0/0:11,0:11:17:0,17,338 ./.:3,0:3:.:0,0,0       0/0:9,0:9:27:0,27,350   0/0:9,0:9:27:0,27,338   0/0:11,0:11:33:0,33,395 0/0:19,0:19:0:0,0,338   0/0:7,0:7:5:0,5,170     0/0:3,0:3:0:0,0,42      0/0:11,0:11:30:0,30,450    0/0:6,0:6:18:0,18,140   0/0:8,0:8:0:0,0,205     0/0:6,0:6:18:0,18,200   ./.:2,0:2:.:0,0,0       ./.:3,0:3:.:0,0,0       0/0:8,0:8:21:0,21,315   0/1:11,2:13:10:10,0,384 0/1:6,2:9:25:25,0,226   0/0:8,0:8:24:0,24,308      0/1:1,2:3:33:75,0,33    0/0:6,0:6:18:0,18,239   0/1:6,2:8:26:26,0,178   0/0:6,0:6:3:0,3,181     0/0:12,0:12:0:0,0,265   0/0:12,0:12:0:0,0,306   0/0:12,0:12:30:0,30,450 0/0:6,0:6:18:0,18,224      0/0:7,0:7:21:0,21,292   0/0:8,0:8:24:0,24,288   0/0:6,0:6:15:0,15,225   0/0:2,0:2:6:0,6,57      0/0:4,0:4:12:0,12,141   0/0:7,0:7:5:0,5,182     0/0:6,0:6:18:0,18,224   0/0:5,0:5:15:0,15,170   0/0:4,0:4:12:0,12,143      0/0:12,0:12:33:0,33,495 0/0:5,0:5:0:0,0,125     0/0:9,0:9:27:0,27,286   0/0:8,0:8:24:0,24,274   0/0:7,0:7:21:0,21,258   0/0:13,0:13:39:0,39,493 0/0:1,0:1:3:0,3,42      0/0:4,0:4:12:0,12,107   0/0:8,0:8:24:0,24,281      0/0:9,0:9:27:0,27,364   0/0:4,0:4:12:0,12,141   0/0:8,0:8:24:0,24,296   0/0:8,0:8:0:0,0,229     0/0:5,0:5:0:0,0,99      0/0:8,0:8:21:0,21,315   0/1:4,2:6:32:32,0,69    0/0:4,0:4:12:0,12,143      0/0:2,0:2:6:0,6,72      0/0:7,0:7:21:0,21,254   0/1:1,4:6:27:140,0,27   0/0:5,0:5:15:0,15,197   0/0:7,0:7:21:0,21,254   0/0:13,0:13:30:0,30,450 0/0:8,0:8:24:0,24,300   0/1:2,2:4:27:38,0,27    0/1:2,2:4:78:78,0,78       0/0:11,0:11:27:0,27,405 0/0:4,0:4:12:0,12,167   0/0:15,0:15:3:0,3,517   0/0:10,0:10:0:0,0,232   0/0:12,0:12:33:0,33,495 0/0:6,0:6:0:0,0,145     0/0:1,0:1:3:0,3,30      1/1:0,2:2:6:49,6,0      0/1:5,2:7:28:28,0,176      0/1:1,2:3:33:40,0,33    0/0:1,0:1:3:0,3,30      0/1:2,4:6:66:81,0,66    0/0:3,0:3:9:0,9,99      0/0:3,0:3:0:0,0,15      0/0:1,0:1:3:0,3,15      0/1:4,2:6:31:31,0,149   0/0:2,0:2:6:0,6,840/0:2,0:2:6:0,6,72       0/1:2,2:4:37:37,0,72    0/0:3,0:3:9:0,9,113     0/0:1,0:1:3:0,3,15      0/0:2,0:2:6:0,6,57      0/0:11,0:11:24:0,24,360 0/0:4,0:4:12:0,12,90    0/0:4,0:4:12:0,12,141   0/0:3,0:3:9:0,9,990/0:4,0:4:12:0,12,114    0/0:10,0:10:27:0,27,405 0/0:4,0:4:12:0,12,129   0/0:4,0:4:12:0,12,107   0/0:4,0:4:0:0,0,84      0/0:4,0:4:12:0,12,90

**Comment by chaimol** [comment]
you input the vcf file lack of vcf header.smcpp need analysis the vcf header 
```
##contig=<ID=Chr01,assembly=ref.fa,length=231951030>
##contig=<ID=Chr02,assembly=ref.fa,length=121531020>
```
frome header to extract the chr id and chr length.

So you must be provide a normal vcf header.
