### ISSUE TITLE
smc++ estimate Error

### ISSUE THREAD

**Issue by lamlitman** [popgenmethods/smcpp#238]
I am using the conda installed smc++ 
I finished the vcf2smc without any error
then i used this command 

`smc++ estimate -o All-1/ -t 1.16e-8 contig-A1/*.smc.gz`

and received this error report 

```
1753 smcpp.commands.estimate WARNING The per-generation mutation rate is calculated to be 5.8e-13. Is this correct?
1753 smcpp.analysis INFO Loading data...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/public/home/acsg9wshyg/anaconda3/envs/smcpp/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/public/home/acsg9wshyg/anaconda3/envs/smcpp/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/public/home/acsg9wshyg/anaconda3/envs/smcpp/lib/python3.5/site-packages/smcpp/estimation_tools.py", line 182, in _load_data_helper
    A = pd.read_csv(fn, sep=' ', comment="#", header=None).values
  File "/public/home/acsg9wshyg/anaconda3/envs/smcpp/lib/python3.5/site-packages/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/public/home/acsg9wshyg/anaconda3/envs/smcpp/lib/python3.5/site-packages/pandas/io/parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/public/home/acsg9wshyg/anaconda3/envs/smcpp/lib/python3.5/site-packages/pandas/io/parsers.py", line 762, in __init__
    self._make_engine(self.engine)
  File "/public/home/acsg9wshyg/anaconda3/envs/smcpp/lib/python3.5/site-packages/pandas/io/parsers.py", line 966, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/public/home/acsg9wshyg/anaconda3/envs/smcpp/lib/python3.5/site-packages/pandas/io/parsers.py", line 1582, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 565, in pandas._libs.parsers.TextReader.__cinit__ (pandas/_libs/parsers.c:6260)
pandas.errors.EmptyDataError: No columns to parse from file
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/public/home/acsg9wshyg/anaconda3/envs/smcpp/bin/smc++", line 9, in <module>
    load_entry_point('smcpp==1.3.21.dev0+ng54170d0.d20170114', 'console_scripts', 'smc++')()
  File "/public/home/acsg9wshyg/anaconda3/envs/smcpp/lib/python3.5/site-packages/smcpp/frontend/console.py", line 23, in main
    cmds[args.command].main(args)
  File "/public/home/acsg9wshyg/anaconda3/envs/smcpp/lib/python3.5/site-packages/smcpp/commands/estimate.py", line 86, in main
    analysis = Analysis(args.data, args)
  File "/public/home/acsg9wshyg/anaconda3/envs/smcpp/lib/python3.5/site-packages/smcpp/analysis.py", line 255, in __init__
    BaseAnalysis.__init__(self, files, args)
  File "/public/home/acsg9wshyg/anaconda3/envs/smcpp/lib/python3.5/site-packages/smcpp/analysis.py", line 40, in __init__
    self._load_data(files)
  File "/public/home/acsg9wshyg/anaconda3/envs/smcpp/lib/python3.5/site-packages/smcpp/analysis.py", line 50, in _load_data
    self._contigs = estimation_tools.load_data(files)
  File "/public/home/acsg9wshyg/anaconda3/envs/smcpp/lib/python3.5/site-packages/smcpp/estimation_tools.py", line 216, in load_data
    obs = list(p.map(_load_data_helper, files))
  File "/public/home/acsg9wshyg/anaconda3/envs/smcpp/lib/python3.5/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/public/home/acsg9wshyg/anaconda3/envs/smcpp/lib/python3.5/multiprocessing/pool.py", line 644, in get
    raise self._value
pandas.errors.EmptyDataError: No columns to parse from file
```

Is it something wrong with my inputted smc.gz files?

**Comment by MingzuyuPan** [comment]
Hi,
I met this issue too. Have you solved this problem? Any information would be helpful!
Thanks!
