### ISSUE TITLE
docker run smc++: NotImplementedError: seek not implemented in files compressed by method 1

### ISSUE THREAD

**Issue by xgdong** [popgenmethods/smcpp#244]
I use docker to run smc++ , an error occurs as below, I don't konw what the problem is, anyone has suggestions?
Traceback (most recent call last):
  File "/usr/local/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.15.4.dev18+gca077da.d20210316', 'console_scripts', 'smc++')()
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev18+gca077da.d20210316-py3.8-linux-x86_64.egg/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev18+gca077da.d20210316-py3.8-linux-x86_64.egg/smcpp/commands/vcf2smc.py", line 128, in main
    vcf = VariantFile(args.vcf)
  File "pysam/libcbcf.pyx", line 4036, in pysam.libcbcf.VariantFile.__init__
  File "pysam/libcbcf.pyx", line 4299, in pysam.libcbcf.VariantFile.open
  File "pysam/libchtslib.pyx", line 516, in pysam.libchtslib.HTSFile.tell
NotImplementedError: seek not implemented in files compressed by method 1

**Comment by xgdong** [comment]
> I use docker to run smc++ , an error occurs as below, I don't konw what the problem is, anyone has suggestions? Traceback (most recent call last): File "/usr/local/bin/smc++", line 11, in load_entry_point('smcpp==1.15.4.dev18+gca077da.d20210316', 'console_scripts', 'smc++')() File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev18+gca077da.d20210316-py3.8-linux-x86_64.egg/smcpp/frontend/console.py", line 26, in main cmds[args.command].main(args) File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev18+gca077da.d20210316-py3.8-linux-x86_64.egg/smcpp/commands/vcf2smc.py", line 128, in main vcf = VariantFile(args.vcf) File "pysam/libcbcf.pyx", line 4036, in pysam.libcbcf.VariantFile.**init** File "pysam/libcbcf.pyx", line 4299, in pysam.libcbcf.VariantFile.open File "pysam/libchtslib.pyx", line 516, in pysam.libchtslib.HTSFile.tell NotImplementedError: seek not implemented in files compressed by method 1

I have solved the issue, the error occurs because the VCF file needs compressed following the BGZF format (needed to be bgzip), not gzip.
