### ISSUE TITLE
RuntimeError: erroneous average coalescence time

### ISSUE THREAD

**Issue by danrans123** [popgenmethods/smcpp#248]
Dear Terhorst,

While using SMC++ v1.13.0, I encountered the runtime errors:
2551 smcpp.analysis.base INFO theta: 0.000100
2551 smcpp.analysis.base INFO rho: 0.000100
2551 smcpp.data_filter INFO Loading data...
3871 smcpp.data_filter INFO 0.95 Gb of data
3893 smcpp.data_filter INFO 1 population
95252 smcpp.optimize.plugins.progress_printer INFO Starting EM algorithm...
95252 smcpp.optimize.plugins.progress_printer INFO EM iteration 1 of 1...
95252 smcpp.analysis.base INFO Running E-step
119367 smcpp.analysis.base INFO E-step completed
119368 smcpp.optimize.plugins.loglikelihood_monitor INFO Loglik: -69716330.719036
6272486 smcpp.optimize.plugins.progress_printer INFO Current model:

-1.99 -1.99 -0.47  1.53  3.23  4.00  3.50  1.88  0.90  1.99  2.28  2.06  1.70
 0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.62  0.62  0.62  0.62  0.62  0.62  0.62  0.62  4.64  4.64  4.64  4.64  4.64  4.64  4.64  4.64  4.64 25.33 25.33 25.33 25.33 25.33 25.33 25.33 25.33 25.33 54.33 54.33 54.33 54.33 54.33 54.33 54.33 54.33 33.27 33.27 33.27 33.27 33.27 33.27 33.27 33.27 33.27  6.55  6.55  6.55  6.55  6.55  6.55  6.55  6.55  6.55  2.47  2.47  2.47  2.47  2.47  7.34  7.34  7.34  7.34  7.34  7.34  7.34  7.34  7.34  7.34  7.34  7.34  9.76  9.76  9.76  9.76  9.76  9.76  9.76  7.84  7.84  7.84  7.84  7.84  5.48
6272497 smcpp.optimize.plugins.ascii_plotter INFO Plot of current model:


   1e+06 ++--+-----+--+-+---+-----+--++----+-----+--++---+-----+--+-+---+++
         +              +             +              +      Pop. 1 ****** +
         +                           B*****                               +
         +                      B*****     B*****                         +
         |                      *               *                         |
  100000 ++                     *                *                B****  ++
         +                     *                 B*****   B*******    B***B
         +                B*****                       *  *               +
         +                *                           B****               +
   10000 ++               *                                              ++
         +               *                                                +
         +          B*****                                                +
         +           *                                                    +
         +          *   +             +              +              +     +
    1000 B*****B*****-+-+---+-----+--++----+-----+--++---+-----+--+-+---+++
         10            100           1000          10000          100000
                                    Generations

6272527 smcpp.data_filter INFO Loading data...
6274013 smcpp.data_filter INFO 0.95 Gb of data
6274019 smcpp.data_filter INFO 1 population
Traceback (most recent call last):
  File "/gss1/App_dir/anaconda3/envs/smcpp/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.15.3', 'console_scripts', 'smc++')()
  File "/gss1/App_dir/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/gss1/App_dir/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/commands/estimate.py", line 47, in main
    analysis = Analysis(args.data, args)
  File "/gss1/App_dir/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/analysis/analysis.py", line 88, in __init__
    self._init_regularization(args)
  File "/gss1/App_dir/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/analysis/analysis.py", line 121, in _init_regularization
    self._penalty = abs(self.Q()) * (10 ** -args.regularization_penalty)
  File "/gss1/App_dir/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/analysis/base.py", line 124, in Q
    qq = [self._ims[pop].Q(separate=True) for pop in self._ims]
  File "/gss1/App_dir/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/analysis/base.py", line 124, in <listcomp>
    qq = [self._ims[pop].Q(separate=True) for pop in self._ims]
  File "smcpp/_smcpp.pyx", line 285, in smcpp._smcpp._PyInferenceManager.Q
  File "smcpp/_smcpp.pyx", line 280, in smcpp._smcpp._PyInferenceManager.Q
RuntimeError: erroneous average coalescence time
7019 smcpp.analysis.base INFO theta: 0.000100
7020 smcpp.analysis.base INFO rho: 0.000100
7020 smcpp.data_filter INFO Loading data...
8288 smcpp.data_filter INFO 0.95 Gb of data
8315 smcpp.data_filter INFO 1 population
29431 smcpp.optimize.plugins.progress_printer INFO Starting EM algorithm...
29432 smcpp.optimize.plugins.progress_printer INFO EM iteration 1 of 1...
29432 smcpp.analysis.base INFO Running E-step
52930 smcpp.analysis.base INFO E-step completed
52932 smcpp.optimize.plugins.loglikelihood_monitor INFO Loglik: -69716201.969917
13166211 smcpp.optimize.plugins.ascii_plotter INFO Plot of current model:


   1e+06 ++--+-----+--++---+-----+-+-+---+----+--+-+---+----+--++----+---++
         +             +             +             +        Pop. 1 ****** +
         +                       B***B**B****                             +
         +                        *         B***              B**         +
         |                    B***             *              *  B*       |
  100000 ++                   *                 *         B****    B**   ++
         +                B***                 B***        *         *    +
         +                 *                       B*******          *    +
         +                *                        B                 B**  +
   10000 ++            B***                                            * ++
         +             *                                               B**+
         +             *                                                  *
         +         B****                                                  +
         +          *  +             +             +            +         +
    1000 B**B***B***--++---+-----+-+-+---+----+--+-+---+----+--++----+---++
         10           100           1000         10000        100000
                                    Generations

13166222 smcpp.optimize.plugins.progress_printer INFO Current model:

-1.99 -1.99 -1.99 -1.12  0.24  1.68  2.84  3.64  4.01  4.01  3.36  1.93  0.74  1.29  2.52  3.16  2.96  2.11  1.07  0.10 -0.87
 0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.14  0.33  0.33  0.33  0.33  0.33  0.33  1.27  1.27  1.27  1.27  1.27  5.34  5.34  5.34  5.34  5.34 17.19 17.19 17.19 17.19 17.19 17.19 37.97 37.97 37.97 37.97 37.97 54.97 54.97 54.97 54.97 54.97 54.97 54.97 54.97 54.97 54.97 54.97 28.91 28.91 28.91 28.91 28.91  6.88  6.88  6.88  6.88  6.88  2.10  3.63  3.63  3.63  3.63  3.63  3.63  3.63  3.63  3.63  3.63  3.63 12.42 12.42 12.42 12.42 12.42 23.63 23.63 23.63 23.63 19.27 19.27 19.27  8.25  8.25  8.25  8.25  2.91  2.91  2.91  1.11  1.11  1.11  1.11  0.42
13166230 smcpp.data_filter INFO Loading data...
13167709 smcpp.data_filter INFO 0.95 Gb of data
13167716 smcpp.data_filter INFO 1 population
Traceback (most recent call last):
  File "/gss1/App_dir/anaconda3/envs/smcpp/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.15.3', 'console_scripts', 'smc++')()
  File "/gss1/App_dir/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/gss1/App_dir/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/commands/estimate.py", line 47, in main
    analysis = Analysis(args.data, args)
  File "/gss1/App_dir/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/analysis/analysis.py", line 88, in __init__
    self._init_regularization(args)
  File "/gss1/App_dir/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/analysis/analysis.py", line 121, in _init_regularization
    self._penalty = abs(self.Q()) * (10 ** -args.regularization_penalty)
  File "/gss1/App_dir/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/analysis/base.py", line 124, in Q
    qq = [self._ims[pop].Q(separate=True) for pop in self._ims]
  File "/gss1/App_dir/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/analysis/base.py", line 124, in <listcomp>
    qq = [self._ims[pop].Q(separate=True) for pop in self._ims]
  File "smcpp/_smcpp.pyx", line 285, in smcpp._smcpp._PyInferenceManager.Q
  File "smcpp/_smcpp.pyx", line 280, in smcpp._smcpp._PyInferenceManager.Q
RuntimeError: erroneous average coalescence time
7776 smcpp.analysis.base INFO theta: 0.000100
7776 smcpp.analysis.base INFO rho: 0.000100
7777 smcpp.data_filter INFO Loading data...
9028 smcpp.data_filter INFO 0.95 Gb of data
9048 smcpp.data_filter INFO 1 population
27481 smcpp.optimize.plugins.progress_printer INFO Starting EM algorithm...
27481 smcpp.optimize.plugins.progress_printer INFO EM iteration 1 of 1...
27481 smcpp.analysis.base INFO Running E-step
52560 smcpp.analysis.base INFO E-step completed
52571 smcpp.optimize.plugins.loglikelihood_monitor INFO Loglik: -69716979.687712
2419015 smcpp.optimize.plugins.progress_printer INFO Current model:

 1.40  4.01  3.72  0.91
 4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07  4.07 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 54.96 41.24 41.24 41.24 41.24 41.24 41.24 41.24 41.24 41.24 41.24 41.24 41.24 41.24 41.24 41.24 41.24 41.24 41.24 41.24 41.24 41.24 41.24 41.24 41.24  2.48
2419047 smcpp.optimize.plugins.ascii_plotter INFO Plot of current model:


   1e+06 ++-------+------+-----+----+---+--+--+--+-----------------+-----++
         +                                       +          Pop. 1 ****** +
         +                               B*****************               +
         +                               *                B***************+
         +                               *                               *+
         +                               *                               *+
         |                               *                               *|
  100000 ++                              *                               *+
         +                               *                                *
         +                               *                                *
         *********************************                                *
         +                                                                *
         +                                                                B
         |                                       +                        |
   10000 ++-------+------+-----+----+---+--+--+--+-----------------+-----++
                                               100000
                                    Generations

2419060 smcpp.data_filter INFO Loading data...
2420694 smcpp.data_filter INFO 0.95 Gb of data
2420701 smcpp.data_filter INFO 1 population
Traceback (most recent call last):
  File "/gss1/App_dir/anaconda3/envs/smcpp/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.15.3', 'console_scripts', 'smc++')()
  File "/gss1/App_dir/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/gss1/App_dir/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/commands/estimate.py", line 47, in main
    analysis = Analysis(args.data, args)
  File "/gss1/App_dir/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/analysis/analysis.py", line 88, in __init__
    self._init_regularization(args)
  File "/gss1/App_dir/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/analysis/analysis.py", line 121, in _init_regularization
    self._penalty = abs(self.Q()) * (10 ** -args.regularization_penalty)
  File "/gss1/App_dir/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/analysis/base.py", line 124, in Q
    qq = [self._ims[pop].Q(separate=True) for pop in self._ims]
  File "/gss1/App_dir/anaconda3/envs/smcpp/lib/python3.7/site-packages/smcpp/analysis/base.py", line 124, in <listcomp>
    qq = [self._ims[pop].Q(separate=True) for pop in self._ims]
  File "smcpp/_smcpp.pyx", line 285, in smcpp._smcpp._PyInferenceManager.Q
  File "smcpp/_smcpp.pyx", line 280, in smcpp._smcpp._PyInferenceManager.Q
RuntimeError: erroneous average coalescence time

my estimation command:
smc++ estimate --cores 2 --timepoints 10  20000 -o ./result/model_time 6.1e-9 ./out/*.smc.gz
smc++ estimate --cores 2 --timepoints 10  20000 -o ./result/model_knots --knots 15 6.1e-9 ./out/*.smc.gz
smc++ estimate --cores 2 -o ./result/model 6.1e-9 ./out/*.smc.gz 

Is there any problem with my command line? 

Thank you!

**Comment by esohkevin** [comment]
I am experiencing the same issue with every run after adding the `--timepoints` option of `estimate`, but only occasionally without the option. This is after using the `--mask` option in the `vcf2smc` step to ensure there no erroneous runs of homozygosity. Not sure what might be the cause.
