### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'seaborn-ticks'

### ISSUE THREAD

**Issue by sahwa** [popgenmethods/smcpp#251]
Hi,

I installed on wsl2 using ```pip install git+https://github.com/popgenmethods/smcpp```

But when I tried to run ``./smc++`` I get the error:

```
Traceback (most recent call last):
  File "/home/sam/.local/lib/python3.10/site-packages/matplotlib/style/core.py", line 137, in use
    style = _rc_params_in_file(style)
  File "/home/sam/.local/lib/python3.10/site-packages/matplotlib/__init__.py", line 866, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/sam/.local/lib/python3.10/site-packages/matplotlib/__init__.py", line 843, in _open_file_or_url
    with open(fname, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'seaborn-ticks'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sam/.local/bin/./smc++", line 5, in <module>
    from smcpp.frontend.console import main
  File "/home/sam/.local/lib/python3.10/site-packages/smcpp/frontend/console.py", line 4, in <module>
    from .. import commands, version, defaults, _smcpp
  File "/home/sam/.local/lib/python3.10/site-packages/smcpp/commands/__init__.py", line 1, in <module>
    from . import vcf2smc, estimate, split, chunk, cite, plot, \
  File "/home/sam/.local/lib/python3.10/site-packages/smcpp/commands/plot.py", line 9, in <module>
    from .. import util, plotting, model
  File "/home/sam/.local/lib/python3.10/site-packages/smcpp/plotting.py", line 6, in <module>
    matplotlib.style.use("seaborn-ticks")
  File "/home/sam/.local/lib/python3.10/site-packages/matplotlib/style/core.py", line 139, in use
    raise OSError(
OSError: 'seaborn-ticks' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
```

Any idea what the issue is?

Thanks.

**Comment by terhorst** [comment]
What version of matplotlib do you have installed?

**Comment by ericspan** [comment]
I had this issue with matplotlib 3.8.1. Going to 3.7.3 fixed it.
