### ISSUE TITLE
PermissionError: [Errno 13] could not open variant (vcf) file

### ISSUE THREAD

**Issue by chenchengaaaaa** [popgenmethods/smcpp#254]
I wanna tranfer the vcf file to the smc file, however i met a errno 13 siad that  the smc can't open the vcf file due to have no permmission, so what should i do to sovle this error? my conmand and log were shown at below.

$docker run --rm -v $PWD:/mnt terhorst/smcpp:latest  vcf2smc 95.vcf.gz   trans LG01 BJ:BJCP_F10

1036 smcpp.commands.vcf2smc WARNING Neither missing cutoff (-c) or mask (-m) has been specified. This means that stretches of
 the chromosome that do not have any VCF entries (for example, centromeres) will be interpreted as homozygous recessive.
1036 smcpp.commands.vcf2smc INFO Population 1:
1036 smcpp.commands.vcf2smc INFO Distinguished lineages: BJCP_F10:0, BJCP_F10:1
1036 smcpp.commands.vcf2smc INFO Undistinguished lineages: 
[E::hts_open_format] Failed to open file "95.vcf.gz" : Permission denied
Traceback (most recent call last):
  File "/usr/local/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.15.4.dev18+gca077da.d20210316', 'console_scripts', 'smc++')()
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev18+gca077da.d20210316-py3.8-linux-x86_64.egg/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/usr/local/lib/python3.8/dist-packages/smcpp-1.15.4.dev18+gca077da.d20210316-py3.8-linux-x86_64.egg/smcpp/commands/vcf2smc.py", line 128, in main
    vcf = VariantFile(args.vcf)
  File "pysam/libcbcf.pyx", line 4036, in pysam.libcbcf.VariantFile.__init__
  File "pysam/libcbcf.pyx", line 4261, in pysam.libcbcf.VariantFile.open
PermissionError: [Errno 13] could not open variant file `b'95.vcf.gz'`: Permission denied

**Comment by terhorst** [comment]
I think this is an issue with your Docker configuration, see https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker.
