### ISSUE TITLE
`GLIBC_2.14' not found

### ISSUE THREAD

**Issue by mjmontague** [popgenmethods/smcpp#27]
I installed via the sh script (smcpp-1.9.2-Linux-x86_64.sh):

SMC++ has been installed to /home/montag/smcpp. To run it, type:
    $ source /home/montag/smcpp/bin/activate
    $ smc++
dbus post-link :: /etc/machine-id not found ..
dbus post-link :: .. using /proc/sys/kernel/random/boot_id
installation finished.
Do you wish the installer to prepend the smcpp install location
to PATH in your /home/montag/.bashrc ? [yes|no]
[no] >>> yes

But when I call the program:

source /home/montag/smcpp/bin/activate
smc++

This is the output:

Traceback (most recent call last):
  File "/home/montag/smcpp/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.9.2', 'console_scripts', 'smc++')()
  File "/home/montag/smcpp/lib/python3.5/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/montag/smcpp/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/home/montag/smcpp/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/montag/smcpp/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/montag/smcpp/lib/python3.5/site-packages/smcpp/frontend/console.py", line 3, in <module>
    from .. import commands
  File "/home/montag/smcpp/lib/python3.5/site-packages/smcpp/commands/__init__.py", line 1, in <module>
    from . import vcf2smc, estimate, split, cite, plot, posterior, version
  File "/home/montag/smcpp/lib/python3.5/site-packages/smcpp/commands/estimate.py", line 14, in <module>
    from ..analysis import Analysis
  File "/home/montag/smcpp/lib/python3.5/site-packages/smcpp/analysis.py", line 11, in <module>
    from . import estimation_tools, _smcpp, util, logging, jcsfs, spline
  File "/home/montag/smcpp/lib/python3.5/site-packages/smcpp/estimation_tools.py", line 14, in <module>
    from . import _smcpp, util
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/montag/smcpp/lib/python3.5/site-packages/smcpp/_smcpp.cpython-35m-x86_64-linux-gnu.so)

**Comment by terhorst** [comment]
This has been reported to me previously so I added a [FAQ to the README](https://github.com/popgenmethods/smcpp/blob/master/README.rst#frequently-asked-questions).
