### ISSUE TITLE
install error: requirements not met

### ISSUE THREAD

**Issue by asifzubair** [popgenmethods/smcpp#35]
I installed SMC++ using the `conda` command. However, I am getting the following error:
```
(0)> smc++ -h
Traceback (most recent call last):
  File "/home/cmb-07/sn1/asifzuba/software_frozen/src/anaconda/envs/smc/bin/smc++", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/cmb-07/sn1/asifzuba/software_frozen/src/anaconda/envs/smc/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/home/cmb-07/sn1/asifzuba/software_frozen/src/anaconda/envs/smc/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/home/cmb-07/sn1/asifzuba/software_frozen/src/anaconda/envs/smc/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/cmb-07/sn1/asifzuba/software_frozen/src/anaconda/envs/smc/lib/python3.5/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/home/cmb-07/sn1/asifzuba/software_frozen/src/anaconda/envs/smc/lib/python3.5/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/cmb-07/sn1/asifzuba/software_frozen/src/anaconda/envs/smc/lib/python3.5/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ad>=1.3.2' distribution was not found and is required by smcpp
```
However, `ad` is clearly installed:
```
(smc) > conda list
# packages in environment at /home/cmb-07/sn1/asifzuba/software_frozen/src/anaconda/envs/smc:
#
ad                        1.3.2                      py_0    terhorst
appdirs                   1.4.3                    py35_0    conda-forge
bcftools                  1.5                           0    bioconda
bzip2                     1.0.6                         1    conda-forge
certifi                   2017.4.17                py35_0    conda-forge
curl                      7.52.1                        0    conda-forge
cycler                    0.10.0                   py35_0    conda-forge
dbus                      1.10.10                       3    conda-forge
expat                     2.2.1                         0    conda-forge
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
gettext                   0.19.7                        1    conda-forge
glib                      2.51.4                        0    conda-forge
gmp                       6.1.0                         3    conda-forge
gnuplot                   4.6.0                         1    bioconda
gsl                       2.2.1                         0  
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         2    conda-forge
htslib                    1.5                           0    bioconda
icu                       58.1                          1    conda-forge
jpeg                      9b                            0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.14                          4    conda-forge
libpng                    1.6.28                        0    conda-forge
libxcb                    1.12                          1    conda-forge
libxml2                   2.9.4                         4    conda-forge
matplotlib                2.0.2               np113py35_0    conda-forge
mpc                       1.0.3                         4    conda-forge
mpfr                      3.1.5                         0    conda-forge
nomkl                     1.0                           0  
numpy                     1.13.0             py35_nomkl_0  [nomkl]
openblas                  0.2.19                        2    conda-forge
openssl                   1.0.2l                        0  
pandas                    0.20.2              np113py35_1    conda-forge
pcre                      8.39                          0    conda-forge
pip                       9.0.1                    py35_1  
pyparsing                 2.2.0                    py35_0    conda-forge
pyqt                      5.6.0                    py35_4    conda-forge
pysam                     0.11.2.2                 py35_1    bioconda
python                    3.5.3                         1  
python-dateutil           2.6.0                    py35_0    conda-forge
pytz                      2017.2                   py35_0    conda-forge
qt                        5.6.2                         3    conda-forge
readline                  6.2                           2  
samtools                  1.5                           0    bioconda
scipy                     0.19.1          np113py35_nomkl_0  [nomkl]
setuptools                33.1.1                   py35_0    conda-forge
setuptools_scm            1.15.6                   py35_0    conda-forge
sip                       4.18                     py35_1    conda-forge
six                       1.10.0                   py35_1    conda-forge
smcpp                     1.9.4                    py35_0    terhorst
sqlite                    3.13.0                        0  
system                    5.8                           2  
tk                        8.5.18                        0  
tornado                   4.5.1                    py35_0    conda-forge
tqdm                      4.14.0                   py35_0    conda-forge
wheel                     0.29.0                   py35_0  
wrapt                     1.10.8                   py35_0    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.2                         1  
zlib                      1.2.8                         3  
```

Can someone suggest what is happening ? Thanks! 

PS: I see the same error even if I install using the linux shell script from Releases.

**Comment by asifzubair** [comment]
Okay, I got around this by doing a `pip install`:
```
(1)> smc++ -h
usage: smc++ [-h] {cite,estimate,plot,posterior,split,vcf2smc,version} ...

positional arguments:
  {cite,estimate,plot,posterior,split,vcf2smc,version}
    cite                Print citation information for SMC++
    estimate            Estimate size history for one population
    plot                Plot size history from fitted model
    posterior           Store/visualize posterior decoding of TMRCA
    split               Estimate split time in two population model
    vcf2smc             Convert VCF to SMC++ format
    version             Print version string

optional arguments:
  -h, --help            show this help message and exit
```

But, I am still confused why the install command in the README not work. Thanks!

**Comment by terhorst** [comment]
Thanks for reporting. I think this should be fixed (without having to manually install the package using ``pip``). You'll need to delete any locally installed/cached copies of the ``ad`` conda package and reinstall it from my conda repository.

**Comment by asifzubair** [comment]
Thank you, @terhorst . Would you suggest that I install from your conda repo, even if I have `pip` installed it ?
