### ISSUE TITLE
equating knots in the json file with interpolated plots

### ISSUE THREAD

**Issue by grahamgower** [popgenmethods/smcpp#43]
I've extracted the spline interpolated points using `smc++ plot --csv -g $gen_in_years` (line in the plot below) and overlaid the knots/y data from the final.json file (points in the plot).

I plotted `x = 2 * N0 * gen_in_years * np.cumsum(knots)` vs. `N0 * y`, but this doesn't seem to match up at all with the interpolated data. I had assumed that the 'knots' are the intervals between \t_k, and the 'y' equivalent to \lambda_k (using PSMC notation). Is this not the case? In fact, there are negative entries in my json file for the 'y' vector - I wonder if this could be problematic given the log/exp transformations I see in the smc++ model.py code...

![out](https://user-images.githubusercontent.com/8665077/30736212-0651494c-9fc1-11e7-8a62-c7e1ce7257a4.png)

```
{
    "model": {
        "N0": 568.1818181818182,
        "class": "SMCModel",
        "knots": [
            0.18477534329799228,
            0.2167994896245832,
            0.2543738675439954,
            0.29846040966857046,
            0.3501877649602677,
            0.4108801930012947,
            0.4820914660451822,
            0.5656446467665595,
            0.6636787600502335,
            0.7787035536528226,
            0.9136637496514698,
            1.0720144315655231,
            1.2578094971187557,
            1.4758054411000134,
            1.731583125242351,
            2.0316906525220433,
            2.383811003568036,
            2.796958726801247,
            3.2817107177206535,
            3.8504769954611855,
            4.517818408708941,
            5.300819404486459,
            6.2195254029720894,
            7.2974559754809585,
            8.562206963353685,
            10.046156952453629,
            11.787296189556427,
            13.830199161520893,
            16.22716573600676,
            19.03956007780837,
            22.339381618079212,
            26.211108294452803,
            30.75385925040676,
            61.50771850081352,
            123.01543700162703
        ],
        "pid": "pop1",
        "spline_class": "PChipSpline",
        "y": [
            0.5469711356637663,
            0.06603400730297171,
            -0.30989352235575285,
            -0.3291741404826769,
            -0.4575623914195299,
            -0.3539328302081781,
            -0.2068562538766061,
            -0.05671430007922762,
            0.24069799864358998,
            0.43309509702806803,
            0.8942325872318884,
            1.2752705051627928,
            1.653501978788532,
            1.907267066125132,
            2.0610294419310735,
            2.2479242868008464,
            2.1980689952282035,
            2.3849388266872795,
            2.364546795618058,
            2.5149249828113778,
            2.5254214986944525,
            2.60749086341473,
            2.6284049545776806,
            2.62711763898989,
            2.6474920003483953,
            2.6385721954384342,
            2.6806544322948334,
            2.6793541914416874,
            2.779514055607664,
            2.777475960740418,
            2.8814850355238635,
            2.832458691286898,
            3.4659870207971286,
            2.984602538671187,
            4.414566725950484
        ]
    },
    "rho": 8.579595700535552e-05,
    "theta": 0.0001
}
```

**Comment by terhorst** [comment]
The knots are in units of 2N0 generations and do not need to be cumsummed.
The y values are log(N(t)/N0).

**Comment by grahamgower** [comment]
Thanks. I feel rather foolish now, because I see you have a `--knots` option to `smc++ plot`. It needs a couple of small fixes though.

If `defaults.additional_knots` is zero, this breaks the indexing done in `plot_psfs()` - I guess all the knots could be plotted because we don't really know how many additional_knots there were for the .json file in question. Also, when plotting multiple .json files, the `plot_psfs()` 'knots' kwarg is overridden for the first file, and we get an exception on the next iteration of the for loop.
```
Traceback (most recent call last):
  File "/home/grg/virtualenvs/smcpp/bin/smc++", line 11, in <module>
    load_entry_point('smcpp', 'console_scripts', 'smc++')()
  File "/home/grg/src/smcpp/smcpp/frontend/console.py", line 28, in main
    cmds[args.command].main(args)
  File "/home/grg/src/smcpp/smcpp/commands/plot.py", line 80, in main
    knots=args.knots, logy=not args.linear)
  File "/home/grg/src/smcpp/smcpp/plotting.py", line 82, in plot_psfs
    if knots and hasattr(m, '_knots'):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

These changes worked for me.
```
diff --git a/smcpp/plotting.py b/smcpp/plotting.py
index 3910844..10612fb 100644
--- a/smcpp/plotting.py
+++ b/smcpp/plotting.py
@@ -73,15 +73,13 @@ def plot_psfs(psfs, xlim, ylim, xlabel, knots=False, logy=False):
                 ms = [mb]
                 labels = [mb.pid]
             for m, l in zip(ms, labels):
-                ak = len(smcpp.defaults.additional_knots)
                 x = np.cumsum(m.s)
                 y = m.stepwise_values().astype('float')
                 x = np.insert(x, 0, 0)
                 y = np.insert(y, 0, y[0])
                 series.append([l, x, y, my_axplot, off, m.N0, g])
                 if knots and hasattr(m, '_knots'):
-                    knots = m._knots[:-ak]
-                    x2, y2 = (knots, np.exp(m[:-ak].astype('float')))
+                    x2, y2 = (m._knots, np.exp(m[:].astype('float')))
                     # if not logy:
                     #     y *= 1e-3
                     series.append([None, x2, y2, ax.scatter, off, m.N0, g])
```
