### ISSUE TITLE
RuntimeError: context has already been set

### ISSUE THREAD

**Issue by Sabryr** [popgenmethods/smcpp#58]
Error:
(smcp) bash-4.1$ smc++ vcf2smc smcpp/example/example.vcf.gz out/chr1.smc.gz chr1 Pop1:S1,S2
Traceback (most recent call last):
  File "/cluster/home/sabryr/nobackup/smcp/smcp/bin/smc++", line 9, in <module>
    load_entry_point('smcpp==1.9.5.dev45+gb4a1220', 'console_scripts', 'smc++')()
  File "/cluster/home/sabryr/nobackup/smcp/smcp/lib/python3.5/site-packages/smcpp/frontend/console.py", line 22, in main
    mp.set_start_method('forkserver')
  File "/cluster/software/EASYBUILD/Python/3.5.2-foss-2016b/lib/python3.5/multiprocessing/context.py", line 231, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set

OS: CentOS 6.8

Installation method: pip install git+https://github.com/popgenmethods/smcpp, in virtualenv

Is there a way to solve this or is there a way to use this software without the smc++

**Comment by terhorst** [comment]
It's fixed in the devel branch, see #51.

**Comment by Sabryr** [comment]
How do I use  devel branch, when using PIP install. Thank you in advance.

Regards,
Sabry

**Comment by Sabryr** [comment]
Thank you and  I used
pip install git+https://github.com/popgenmethods/smcpp.git@devel

and the error is no more.
