### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by jnaitsaada** [popgenmethods/smcpp#59]
Hi,

I have 2 different Anaconda environments, and in both of them I have problem importing _smcpp from smcpp (I'm using Python 3, and a MacOS machine)

In my first anaconda environment, I have:
>>> from smcpp import _smcpp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/anaconda3/lib/python3.6/site-packages/smcpp/_smcpp.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libopenblasp-r0.2.19.dylib
  Referenced from: /anaconda3/lib/python3.6/site-packages/smcpp/_smcpp.cpython-36m-darwin.so
  Reason: image not found

In my second anaconda environment:
  File "get_csfs.py", line 3, in <module>
    from smcpp import _smcpp, util, estimation_tools
  File "/Users/Juba/MPhil/ASMC/smcpp/estimation_tools.py", line 12, in <module>
    from . import _smcpp, util, logging, model
ImportError: cannot import name '_smcpp'

Do you have an idea to fix one of them ?

Thank you very much.

**Comment by terhorst** [comment]
I'm not sure what causes this error; although I try to provide pre-compiled binaries for MacOS using conda, they are less thoroughly tested than the corresponding Linux version. Did you install the package into a vanilla conda environment? You might want to try building it yourself using pip.

**Comment by terhorst** [comment]
Closing due to inactivity.
