### ISSUE TITLE
KeyError: 'hidden_states'

### ISSUE THREAD

**Issue by fjkfs** [popgenmethods/smcpp#62]
Hi Jonathan,
I am now using 1.11.1 version to analyze the split of two populations, here comes the error.
Do you have any suggestions? 
Here is the message:

843 smcpp.analysis INFO theta: 0.000100
843 smcpp.analysis INFO rho: 0.000100
844 smcpp.data_filter INFO Loading data...
5159 smcpp.data_filter INFO 0.39 Gb of data
5169 smcpp.data_filter INFO 2 populations
5819 smcpp.estimation_tools WARNING Long runs of homozygosity in contig /home/bioke/data/out/EA-OC/EA-OC.NewChr19.smc.gz:
[[61626     0     0   152     0     0    68]]
7508 smcpp.estimation_tools WARNING Long runs of homozygosity in contig /home/bioke/data/out/EA-OC/EA-OC.NewChr20.smc.gz:
[[64999     0     0   152     0     0    68]]
8583 smcpp.estimation_tools WARNING Long runs of homozygosity in contig /home/bioke/data/out/EA-OC/EA-OC.NewChr1.smc.gz:
[[56556     0     0   152     0     0    68]]
Traceback (most recent call last):
  File "/home/bioke/smcpp/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.11.1.dev0', 'console_scripts', 'smc++')()
  File "/home/bioke/smcpp/lib/python3.6/site-packages/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/home/bioke/smcpp/lib/python3.6/site-packages/smcpp/commands/split.py", line 44, in main
    analysis = SplitAnalysis(args.data, args)
  File "/home/bioke/smcpp/lib/python3.6/site-packages/smcpp/analysis.py", line 271, in __init__
    self._init_model(args.pop1, args.pop2)
  File "/home/bioke/smcpp/lib/python3.6/site-packages/smcpp/analysis.py", line 297, in _init_model
    self._hidden_states = d['hidden_states']
KeyError: 'hidden_states'

Thanks,

Fushi

**Comment by terhorst** [comment]
The file format changed between versions. Re-run estimate using the latest version and then pass that to split.
