### ISSUE TITLE
--t1 required when no undistinguished samples (PSMC style)

### ISSUE THREAD

**Issue by jackkamm** [popgenmethods/smcpp#75]
When running with no undistinguished samples (a la PSMC), `smc++ estimate` will output the following error if the `--t1` flag is not provided, because the heuristic for determining t1 will divide by 0:
```
Traceback (most recent call last):
  File "/home/jack/.local/share/virtualenvs/smcpp-Yx5qqfLo/bin/smc++", line 11, in <module>
    load_entry_point('smcpp', 'console_scripts', 'smc++')()
  File "/home/jack/Source/smcpp/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/home/jack/Source/smcpp/smcpp/commands/estimate.py", line 71, in main
    analysis = Analysis(args.data, args)
  File "/home/jack/Source/smcpp/smcpp/analysis.py", line 217, in __init__
    args.t1 = 2. * NeN0 * self._N0 * -np.log(.001) / (n * (n - 1) / 2)                                         
FloatingPointError: divide by zero encountered in double_scalars 
```

**Comment by zacharyhanna** [comment]
Thanks for pointing out the --t1 flag work-around. "n" seems to be the diploid sample size in the args.t1 formula. Would a potential way around this error be to have n = the haploid sample size?
