### ISSUE TITLE
 ERROR Heuristic used to calculate time points has failed, possibly due to having a lot of missing data. Please set the --timepoints option manually.

### ISSUE THREAD

**Issue by mmaalvarez** [popgenmethods/smcpp#86]
Hi, I am running into an error when running the following command:

smc++ estimate -o output --timepoints 0,200 1.25e-8 input_chr*.smc.gz

The log is:

1262 smcpp.analysis.base INFO theta: 0.000100
1263 smcpp.analysis.base INFO rho: 0.000100
1263 smcpp.data_filter INFO Loading data...
14534 smcpp.data_filter INFO 2.94 Gb of data
14552 smcpp.data_filter INFO 1 population
14686 smcpp.estimation_tools WARNING Long runs of homozygosity in contig input_chr5.smc.gz: 
[195855] (base pairs)
14765 smcpp.estimation_tools WARNING Long runs of homozygosity in contig input_chr8.smc.gz: 
[63317] (base pairs)
14783 smcpp.estimation_tools WARNING Long runs of homozygosity in contig input_chr22.smc.gz: 
[70118] (base pairs)
14878 smcpp.estimation_tools WARNING Long runs of homozygosity in contig input_chr3.smc.gz: 
[122714] (base pairs)
14932 smcpp.estimation_tools WARNING Long runs of homozygosity in contig input_chr11.smc.gz: 
[60713] (base pairs)
14963 smcpp.estimation_tools WARNING Long runs of homozygosity in contig input_chr18.smc.gz: 
[61786] (base pairs)
15032 smcpp.estimation_tools WARNING Long runs of homozygosity in contig input_chr6.smc.gz: 
[194397] (base pairs)
15084 smcpp.estimation_tools WARNING Long runs of homozygosity in contig input_chr9.smc.gz: 
[104208] (base pairs)
15227 smcpp.estimation_tools WARNING Long runs of homozygosity in contig input_chr13.smc.gz: 
[60335] (base pairs)
15267 smcpp.estimation_tools WARNING Long runs of homozygosity in contig input_chr14.smc.gz: 
[60315] (base pairs)
15356 smcpp.estimation_tools WARNING Long runs of homozygosity in contig input_chr16.smc.gz: 
[181778] (base pairs)
15464 smcpp.estimation_tools WARNING Long runs of homozygosity in contig input_chr4.smc.gz: 
[113794] (base pairs)
15636 smcpp.estimation_tools WARNING Long runs of homozygosity in contig input_chr20.smc.gz: 
[60422] (base pairs)
70465 smcpp.analysis.analysis ERROR Heuristic used to calculate time points has failed, possibly due to having a lot of missing data. Please set the --timepoints option manually.
Traceback (most recent call last):
  File "/apps/CONDA/4.3.11_PYTHON3/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.14.0.dev0', 'console_scripts', 'smc++')()
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/smcpp/commands/estimate.py", line 74, in main
    analysis = Analysis(args.data, args)
  File "/apps/CONDA/4.3.11_PYTHON3/lib/python3.6/site-packages/smcpp/analysis/analysis.py", line 54, in __init__
    raise RuntimeError()
RuntimeError

It tells me to set the --timepoints manually, but I am already doing so, so I do not know what to do. Any ideas?

Regards

**Comment by terhorst** [comment]
Looks like a bug. Thanks for reporting. I just got back from vacation and will look into this (as well as the other issue you submitted.)

**Comment by zhsiru** [comment]
I encountered the same error, I tried to use SMC++ on exome sequencing data so I masked out all genomic regions that are not in my probe design. It returned the same error even after I manually set the --timepoints.

However when I tested without mask it seems to work.

I installed SMC++ through conda in Aug. Not sure if the bug is still there or I did something wrong.

Thanks!
