### ISSUE TITLE
float division by zero

### ISSUE THREAD

**Issue by yuntwang** [popgenmethods/smcpp#87]
Hi,
@terhorst 
I use the software of smc++(v1.12.1) and encounter a bug.
the command line:
**smc++ estimate --cores 10 -o ./ 0.78e-9 *.smc.gz** 
the error info:
1697 smcpp.analysis INFO theta: 0.000100
1698 smcpp.analysis INFO rho: 0.000100
1698 smcpp.data_filter INFO Loading data...
5217 smcpp.data_filter INFO 0.32 Gb of data
5219 smcpp.data_filter INFO 1 population
5322 smcpp.estimation_tools WARNING Long runs of homozygosity in contig /share/nas1/zhouy/Gexinghua/BMK170606-F624_425_Frog/gexinghua20180528/SMC++/smc/SW/chr1.smc.gz: 
[[295512964         0         0       116]]
47370 smcpp.analysis INFO calculated t1: 4233.510141 gens
Traceback (most recent call last):
  File "/share/nas1/wangyt/software/anaconda3/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.12.1', 'console_scripts', 'smc++')()
  File "/share/nas1/wangyt/software/anaconda3/lib/python3.6/site-packages/smcpp/frontend/console.py", line 26, in main
    cmds[args.command].main(args)
  File "/share/nas1/wangyt/software/anaconda3/lib/python3.6/site-packages/smcpp/commands/estimate.py", line 71, in main
    analysis = Analysis(args.data, args)
  File "/share/nas1/wangyt/software/anaconda3/lib/python3.6/site-packages/smcpp/analysis.py", line 227, in __init__
    self._init_model(args.spline)
  File "/share/nas1/wangyt/software/anaconda3/lib/python3.6/site-packages/smcpp/analysis.py", line 248, in _init_model
    spline_class, self.populations[0])
  File "/share/nas1/wangyt/software/anaconda3/lib/python3.6/site-packages/smcpp/model.py", line 118, in __init__
    self._spline = self._spline_class(self.transformed_knots)
  File "/share/nas1/wangyt/software/anaconda3/lib/python3.6/site-packages/smcpp/spline/cubic.py", line 36, in __init__
    self._fit()
  File "/share/nas1/wangyt/software/anaconda3/lib/python3.6/site-packages/smcpp/spline/pchip.py", line 37, in _fit
    delta = np.diff(y) / h
ZeroDivisionError: float division by zero

How can I deal with it.
Thanks

**Comment by terhorst** [comment]
From the warning, you have a 295Gbp run of homozygous data on chr1. Something is wrong with your VCF I suspect.

**Comment by terhorst** [comment]
Close due to lack of activity.
