### ISSUE TITLE
Conda installation not successful

### ISSUE THREAD

**Issue by oushujun** [popgenmethods/smcpp#94]
Hello,

I was trying to install smc++ with conda.

First I install all dependencies:
`conda install mpfr gmp gsl`

The status output:
Solving environment: done

\#\# Package Plan ##

  environment location: /opt/software/miniconda/4.4.10--GCC-4.9.4

  added / updated specs: 
    - gmp
    - gsl
    - mpfr

The following packages will be UPDATED:

    blas:         1.0-mkl               --> 1.1-openblas                          conda-forge
    gsl:          2.2.1-h0c605f7_3      --> 2.2.1-blas_openblas_4                 conda-forge [blas_openblas]
    numpy:        1.14.3-py36h28100ab_2 --> 1.14.5-py36_blas_openblashd3ea46f_201 conda-forge [blas_openblas]
    scikit-learn: 0.19.1-py36hedc7406_0 --> 0.19.2-py36_blas_openblas_200         conda-forge [blas_openblas]
    scipy:        1.1.0-py36hc49cb51_0  --> 1.1.0-py36_blas_openblashd3ea46f_201  conda-forge [blas_openblas]

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Then install smc++
`conda install -c terhorst -c bioconda smcpp`

The status output:
Solving environment: done

## Package Plan ##

  environment location: /opt/software/miniconda/4.4.10--GCC-4.9.4

  added / updated specs: 
    - smcpp

The following packages will be DOWNGRADED:

    blas:         1.1-openblas                          conda-forge --> 1.0-mkl              
    gsl:          2.2.1-blas_openblas_4                 conda-forge [blas_openblas] --> 2.2.1-h0c605f7_3     
    numpy:        1.14.5-py36_blas_openblashd3ea46f_201 conda-forge [blas_openblas] --> 1.14.3-py36h28100ab_2
    scikit-learn: 0.19.2-py36_blas_openblas_200         conda-forge [blas_openblas] --> 0.19.1-py36hedc7406_0
    scipy:        1.1.0-py36_blas_openblashd3ea46f_201  conda-forge [blas_openblas] --> 1.1.0-py36hc49cb51_0 

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

When I execute `smc++`, it emited errors:
smc++ 
Traceback (most recent call last):
  File "/opt/software/miniconda/4.4.10--GCC-4.9.4/bin/smc++", line 11, in <module>
    load_entry_point('smcpp==1.14.0.dev0', 'console_scripts', 'smc++')()
  File "/opt/software/miniconda/4.4.10--GCC-4.9.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/software/miniconda/4.4.10--GCC-4.9.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/opt/software/miniconda/4.4.10--GCC-4.9.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/opt/software/miniconda/4.4.10--GCC-4.9.4/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/software/miniconda/4.4.10--GCC-4.9.4/lib/python3.6/site-packages/smcpp/__init__.py", line 3, in <module>
    import numpy as np
  File "/opt/software/NumPy/1.11.2--GCC-4.8.5/lib64/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/opt/software/NumPy/1.11.2--GCC-4.8.5/lib64/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/opt/software/NumPy/1.11.2--GCC-4.8.5/lib64/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/opt/software/NumPy/1.11.2--GCC-4.8.5/lib64/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/opt/software/NumPy/1.11.2--GCC-4.8.5/lib64/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: dynamic module does not define module export function (PyInit_multiarray)

It seems like the correct numpy version is not used.

I checked the currect python version: `python --version`
`Python 3.6.6 :: Anaconda, Inc.`

I don't know why the python2.7 version numpy is keep being used and the way to specify the correct version.

Any help appreciated!

Thanks!

Shujun

**Comment by terhorst** [comment]
Yeah I don't know either, it's something related to your conda environment. You might try creating a new conda environment (separate from the root environ) and `source activate`ing it before installing and running SMC++.

**Comment by oushujun** [comment]
Good suggestion! Building a separate conda environment solves the problem. Thanks!

Shujun
